#include "StyleLexers.h"

// ----------------------------------------------------------------------------

KEYWORDLIST KeyWords_AU3 =
{
    "and byref case const continuecase continueloop default dim do else elseif endfunc endif endselect endswitch "
    "endwith enum exit exitloop false for func global if in local next not null or redim return "
    "select static step switch then to true until volatile wend while with",
    "abs acos adlibregister adlibunregister asc ascw asin assign atan autoitsetoption autoitwingettitle "
    "autoitwinsettitle beep binary binarylen binarymid binarytostring bitand bitnot bitor bitrotate bitshift "
    "bitxor blockinput break call cdtray ceiling chr chrw clipget clipput consoleread consolewrite "
    "consolewriteerror controlclick controlcommand controldisable controlenable controlfocus controlgetfocus "
    "controlgethandle controlgetpos controlgettext controlhide controllistview controlmove controlsend "
    "controlsettext controlshow controltreeview cos dec dircopy dircreate dirgetsize dirmove dirremove dllcall "
    "dllcalladdress dllcallbackfree dllcallbackgetptr dllcallbackregister dllclose dllopen dllstructcreate "
    "dllstructgetdata dllstructgetptr dllstructgetsize dllstructsetdata drivegetdrive drivegetfilesystem "
    "drivegetlabel drivegetserial drivegettype drivemapadd drivemapdel drivemapget drivesetlabel "
    "drivespacefree drivespacetotal drivestatus envget envset envupdate eval execute exp filechangedir "
    "fileclose filecopy filecreatentfslink filecreateshortcut filedelete fileexists filefindfirstfile "
    "filefindnextfile fileflush filegetattrib filegetencoding filegetlongname filegetpos filegetshortcut "
    "filegetshortname filegetsize filegettime filegetversion fileinstall filemove fileopen fileopendialog "
    "fileread filereadline filereadtoarray filerecycle filerecycleempty filesavedialog fileselectfolder "
    "filesetattrib filesetend filesetpos filesettime filewrite filewriteline floor ftpsetproxy funcname "
    "guicreate guictrlcreateavi guictrlcreatebutton guictrlcreatecheckbox guictrlcreatecombo "
    "guictrlcreatecontextmenu guictrlcreatedate guictrlcreatedummy guictrlcreateedit guictrlcreategraphic "
    "guictrlcreategroup guictrlcreateicon guictrlcreateinput guictrlcreatelabel guictrlcreatelist "
    "guictrlcreatelistview guictrlcreatelistviewitem guictrlcreatemenu guictrlcreatemenuitem "
    "guictrlcreatemonthcal guictrlcreateobj guictrlcreatepic guictrlcreateprogress guictrlcreateradio "
    "guictrlcreateslider guictrlcreatetab guictrlcreatetabitem guictrlcreatetreeview guictrlcreatetreeviewitem "
    "guictrlcreateupdown guictrldelete guictrlgethandle guictrlgetstate guictrlread guictrlrecvmsg "
    "guictrlregisterlistviewsort guictrlsendmsg guictrlsendtodummy guictrlsetbkcolor guictrlsetcolor "
    "guictrlsetcursor guictrlsetdata guictrlsetdefbkcolor guictrlsetdefcolor guictrlsetfont guictrlsetgraphic "
    "guictrlsetimage guictrlsetlimit guictrlsetonevent guictrlsetpos guictrlsetresizing guictrlsetstate "
    "guictrlsetstyle guictrlsettip guidelete guigetcursorinfo guigetmsg guigetstyle guiregistermsg "
    "guisetaccelerators guisetbkcolor guisetcoord guisetcursor guisetfont guisethelp guiseticon guisetonevent "
    "guisetstate guisetstyle guistartgroup guiswitch hex hotkeyset httpsetproxy httpsetuseragent hwnd inetclose "
    "inetget inetgetinfo inetgetsize inetread inidelete iniread inireadsection inireadsectionnames "
    "inirenamesection iniwrite iniwritesection inputbox int isadmin isarray isbinary isbool isdeclared "
    "isdllstruct isfloat isfunc ishwnd isint iskeyword ismap isnumber isobj isptr isstring log mapappend "
    "mapexists mapkeys mapremove memgetstats mod mouseclick mouseclickdrag mousedown mousegetcursor "
    "mousegetpos mousemove mouseup mousewheel msgbox number objcreate objcreateinterface objevent objget "
    "objname onautoitexitregister onautoitexitunregister opt ping pixelchecksum pixelgetcolor pixelsearch "
    "processclose processexists processgetstats processlist processsetpriority processwait processwaitclose "
    "progressoff progresson progressset ptr random regdelete regenumkey regenumval regread regwrite round run "
    "runas runaswait runwait send sendkeepactive seterror setextended shellexecute shellexecutewait shutdown "
    "sin sleep soundplay soundsetwavevolume splashimageon splashoff splashtexton sqrt srandom statusbargettext "
    "stderrread stdinwrite stdioclose stdoutread string stringaddcr stringcompare stringformat "
    "stringfromasciiarray stringinstr stringisalnum stringisalpha stringisascii stringisdigit stringisfloat "
    "stringisint stringislower stringisspace stringisupper stringisxdigit stringleft stringlen stringlower "
    "stringmid stringregexp stringregexpreplace stringreplace stringreverse stringright stringsplit "
    "stringstripcr stringstripws stringtoasciiarray stringtobinary stringtrimleft stringtrimright stringupper "
    "tan tcpaccept tcpclosesocket tcpconnect tcplisten tcpnametoip tcprecv tcpsend tcpshutdown tcpstartup "
    "timerdiff timerinit tooltip traycreateitem traycreatemenu traygetmsg trayitemdelete trayitemgethandle "
    "trayitemgetstate trayitemgettext trayitemsetonevent trayitemsetstate trayitemsettext traysetclick "
    "trayseticon traysetonevent traysetpauseicon traysetstate traysettooltip traytip ubound udpbind "
    "udpclosesocket udpopen udprecv udpsend udpshutdown udpstartup vargettype winactivate winactive winclose "
    "winexists winflash wingetcaretpos wingetclasslist wingetclientsize wingethandle wingetpos wingetprocess "
    "wingetstate wingettext wingettitle winkill winlist winmenuselectitem winminimizeall winminimizeallundo "
    "winmove winsetontop winsetstate winsettitle winsettrans winwait winwaitactive winwaitclose winwaitnotactive",
    "@appdatacommondir @appdatadir @autoitexe @autoitpid @autoitversion @autoitx64 @com_eventobj @commonfilesdir "
    "@compiled @computername @comspec @cpuarch @cr @crlf @desktopcommondir @desktopdepth @desktopdir @desktopheight "
    "@desktoprefresh @desktopwidth @documentscommondir @error @exitcode @exitmethod @extended @favoritescommondir "
    "@favoritesdir @gui_ctrlhandle @gui_ctrlid @gui_dragfile @gui_dragid @gui_dropid @gui_winhandle @homedrive "
    "@homepath @homeshare @hotkeypressed @hour @ipaddress1 @ipaddress2 @ipaddress3 @ipaddress4 @kblayout @lf "
    "@logondnsdomain @logondomain @logonserver @mday @min @mon @msec @muilang @mydocumentsdir @numparams @osarch "
    "@osbuild @oslang @osservicepack @ostype @osversion @programfilesdir @programscommondir @programsdir "
    "@scriptdir @scriptfullpath @scriptlinenumber @scriptname @sec @startmenucommondir @startmenudir "
    "@startupcommondir @startupdir @sw_disable @sw_enable @sw_hide @sw_lock @sw_maximize @sw_minimize "
    "@sw_restore @sw_show @sw_showdefault @sw_showmaximized @sw_showminimized @sw_showminnoactive @sw_showna "
    "@sw_shownoactivate @sw_shownormal @sw_unlock @systemdir @tab @tempdir @tray_id @trayiconflashing "
    "@trayiconvisible @username @userprofiledir @wday @windowsdir @workingdir @yday @year",
    "{!} {#} {+} {^} {altdown} {altup} {alt} {appskey} {asc} {backspace} {break} {browser_back} "
    "{browser_favorites} {browser_forward} {browser_home} {browser_refresh} {browser_search} {browser_stop} "
    "{bs} {capslock} {ctrldown} {ctrlup} {delete} {del} {down} {end} {enter} {escape} {esc} {f10} {f11} {f12} "
    "{f1} {f2} {f3} {f4} {f5} {f6} {f7} {f8} {f9} {home} {insert} {ins} {lalt} {launch_app1} {launch_app2} "
    "{launch_mail} {launch_media} {lctrl} {left} {lshift} {lwindown} {lwinup} {lwin} {media_next} "
    "{media_play_pause} {media_prev} {media_stop} {numlock} {numpad0} {numpad1} {numpad2} {numpad3} {numpad4} "
    "{numpad5} {numpad6} {numpad7} {numpad8} {numpad9} {numpadadd} {numpaddiv} {numpaddot} {numpadenter} "
    "{numpadmult} {numpadsub} {oem_102} {pause} {pgdn} {pgup} {printscreen} {ralt} {rctrl} {right} {rshift} "
    "{rwindown} {rwinup} {rwin} {scrolllock} {shiftdown} {shiftup} {sleep} {space} {tab} {up} {volume_down} "
    "{volume_mute} {volume_up} {{} {}}",
    "#autoit3wrapper_au3check_parameters #autoit3wrapper_au3check_stop_onwarning #autoit3wrapper_change2cui "
    "#autoit3wrapper_compression #autoit3wrapper_cvswrapper_parameters #autoit3wrapper_icon #autoit3wrapper_outfile "
    "#autoit3wrapper_outfile_type #autoit3wrapper_plugin_funcs #autoit3wrapper_res_comment "
    "#autoit3wrapper_res_description #autoit3wrapper_res_field #autoit3wrapper_res_file_add "
    "#autoit3wrapper_res_fileversion #autoit3wrapper_res_fileversion_autoincrement #autoit3wrapper_res_icon_add "
    "#autoit3wrapper_res_language #autoit3wrapper_res_legalcopyright #autoit3wrapper_res_requestedexecutionlevel "
    "#autoit3wrapper_res_savesource #autoit3wrapper_run_after #autoit3wrapper_run_au3check "
    "#autoit3wrapper_run_before #autoit3wrapper_run_cvswrapper #autoit3wrapper_run_debug_mode "
    "#autoit3wrapper_run_obfuscator #autoit3wrapper_run_tidy #autoit3wrapper_tidy_stop_onerror "
    "#autoit3wrapper_useansi #autoit3wrapper_useupx #autoit3wrapper_usex64 #autoit3wrapper_version #ce "
    "#comments-end #comments-start #cs #endregion #forceref #include #include-once #notrayicon "
    "#obfuscator_ignore_funcs #obfuscator_ignore_variables #obfuscator_parameters #onautoitstartregister #region "
    "#requireadmin #tidy_parameters", 
    "", // Reserved for expand
    "_array1dtohistogram _array2dcreate _arrayadd _arraybinarysearch _arraycoldelete _arraycolinsert "
    "_arraycombinations _arrayconcatenate _arraydelete _arraydisplay _arrayextract _arrayfindall "
    "_arrayfromstring _arrayinsert _arraymax _arraymaxindex _arraymin _arrayminindex _arraypermute _arraypop "
    "_arraypush _arrayreverse _arraysearch _arrayshuffle _arraysort _arrayswap _arraytoclip _arraytostring "
    "_arraytranspose _arraytrim _arrayunique _assert _choosecolor _choosefont _clipboard_changechain "
    "_clipboard_close _clipboard_countformats _clipboard_empty _clipboard_enumformats _clipboard_formatstr "
    "_clipboard_getdata _clipboard_getdataex _clipboard_getformatname _clipboard_getopenwindow "
    "_clipboard_getowner _clipboard_getpriorityformat _clipboard_getsequencenumber _clipboard_getviewer "
    "_clipboard_isformatavailable _clipboard_open _clipboard_registerformat _clipboard_setdata "
    "_clipboard_setdataex _clipboard_setviewer _clipputfile _colorconverthsltorgb _colorconvertrgbtohsl "
    "_colorgetblue _colorgetcolorref _colorgetgreen _colorgetred _colorgetrgb _colorsetcolorref _colorsetrgb "
    "_crypt_decryptdata _crypt_decryptfile _crypt_derivekey _crypt_destroykey _crypt_encryptdata "
    "_crypt_encryptfile _crypt_genrandom _crypt_hashdata _crypt_hashfile _crypt_shutdown _crypt_startup "
    "_date_time_comparefiletime _date_time_dosdatetimetoarray _date_time_dosdatetimetofiletime "
    "_date_time_dosdatetimetostr _date_time_dosdatetoarray _date_time_dosdatetostr _date_time_dostimetoarray "
    "_date_time_dostimetostr _date_time_encodefiletime _date_time_encodesystemtime _date_time_filetimetoarray "
    "_date_time_filetimetodosdatetime _date_time_filetimetolocalfiletime _date_time_filetimetostr "
    "_date_time_filetimetosystemtime _date_time_getfiletime _date_time_getlocaltime _date_time_getsystemtime "
    "_date_time_getsystemtimeadjustment _date_time_getsystemtimeasfiletime _date_time_getsystemtimes "
    "_date_time_gettickcount _date_time_gettimezoneinformation _date_time_localfiletimetofiletime "
    "_date_time_setfiletime _date_time_setlocaltime _date_time_setsystemtime _date_time_setsystemtimeadjustment "
    "_date_time_settimezoneinformation _date_time_systemtimetoarray _date_time_systemtimetodatestr "
    "_date_time_systemtimetodatetimestr _date_time_systemtimetofiletime _date_time_systemtimetotimestr "
    "_date_time_systemtimetotzspecificlocaltime _date_time_tzspecificlocaltimetosystemtime "
    "_dateadd _datedayofweek _datedaysinmonth _datediff _dateisleapyear _dateisvalid _datetimeformat "
    "_datetimesplit _datetodayofweek _datetodayofweekiso _datetodayvalue _datetomonth _dayvaluetodate "
    "_debugarraydisplay _debugbugreportenv _debugcomerror _debugout _debugreport _debugreportex _debugreportvar "
    "_debugsetup _degree _eventlog__backup _eventlog__clear _eventlog__close _eventlog__count "
    "_eventlog__deregistersource _eventlog__full _eventlog__notify _eventlog__oldest _eventlog__open "
    "_eventlog__openbackup _eventlog__read _eventlog__registersource _eventlog__report _excel_bookattach "
    "_excel_bookclose _excel_booklist _excel_booknew _excel_bookopen _excel_bookopentext _excel_booksave "
    "_excel_booksaveas _excel_close _excel_columntoletter _excel_columntonumber _excel_convertformula "
    "_excel_export _excel_filterget _excel_filterset _excel_open _excel_pictureadd _excel_print "
    "_excel_rangecopypaste _excel_rangedelete _excel_rangefind _excel_rangeinsert _excel_rangelinkaddremove "
    "_excel_rangeread _excel_rangereplace _excel_rangesort _excel_rangevalidate _excel_rangewrite "
    "_excel_sheetadd _excel_sheetcopymove _excel_sheetdelete _excel_sheetlist _filecountlines _filecreate "
    "_filelisttoarray _filelisttoarrayrec _fileprint _filereadtoarray _filewritefromarray _filewritelog "
    "_filewritetoline _formatautoitexitcode _formatautoitexitmethod _ftp_close _ftp_command _ftp_connect "
    "_ftp_decodeinternetstatus _ftp_dircreate _ftp_dirdelete _ftp_dirgetcurrent _ftp_dirputcontents "
    "_ftp_dirsetcurrent _ftp_fileclose _ftp_filedelete _ftp_fileget _ftp_filegetsize _ftp_fileopen _ftp_fileput "
    "_ftp_fileread _ftp_filerename _ftp_filetimelohitostr _ftp_findfileclose _ftp_findfilefirst _ftp_findfilenext "
    "_ftp_getlastresponseinfo _ftp_listtoarray _ftp_listtoarray2d _ftp_listtoarrayex _ftp_open "
    "_ftp_progressdownload _ftp_progressupload _ftp_setstatuscallback _getip "
    "_gdiplus_arrowcapcreate _gdiplus_arrowcapdispose _gdiplus_arrowcapgetfillstate _gdiplus_arrowcapgetheight "
    "_gdiplus_arrowcapgetmiddleinset _gdiplus_arrowcapgetwidth _gdiplus_arrowcapsetfillstate "
    "_gdiplus_arrowcapsetheight _gdiplus_arrowcapsetmiddleinset _gdiplus_arrowcapsetwidth _gdiplus_bitmapclonearea "
    "_gdiplus_bitmapcreatefromfile _gdiplus_bitmapcreatefromgraphics _gdiplus_bitmapcreatefromhbitmap "
    "_gdiplus_bitmapcreatehbitmapfrombitmap _gdiplus_bitmapdispose _gdiplus_bitmaplockbits "
    "_gdiplus_bitmapunlockbits _gdiplus_brushclone _gdiplus_brushcreatesolid _gdiplus_brushdispose "
    "_gdiplus_brushgetsolidcolor _gdiplus_brushgettype _gdiplus_brushsetsolidcolor _gdiplus_customlinecapdispose "
    "_gdiplus_decoders _gdiplus_decodersgetcount _gdiplus_decodersgetsize _gdiplus_drawimagepoints "
    "_gdiplus_encoders _gdiplus_encodersgetclsid _gdiplus_encodersgetcount _gdiplus_encodersgetparamlist "
    "_gdiplus_encodersgetparamlistsize _gdiplus_encodersgetsize _gdiplus_fontcreate _gdiplus_fontdispose "
    "_gdiplus_fontfamilycreate _gdiplus_fontfamilydispose _gdiplus_graphicsclear _gdiplus_graphicscreatefromhdc "
    "_gdiplus_graphicscreatefromhwnd _gdiplus_graphicsdispose _gdiplus_graphicsdrawarc _gdiplus_graphicsdrawbezier "
    "_gdiplus_graphicsdrawclosedcurve _gdiplus_graphicsdrawcurve _gdiplus_graphicsdrawellipse "
    "_gdiplus_graphicsdrawimage _gdiplus_graphicsdrawimagerect _gdiplus_graphicsdrawimagerectrect "
    "_gdiplus_graphicsdrawline _gdiplus_graphicsdrawpie _gdiplus_graphicsdrawpolygon _gdiplus_graphicsdrawrect "
    "_gdiplus_graphicsdrawstring _gdiplus_graphicsdrawstringex _gdiplus_graphicsfillclosedcurve "
    "_gdiplus_graphicsfillellipse _gdiplus_graphicsfillpie _gdiplus_graphicsfillpolygon _gdiplus_graphicsfillrect "
    "_gdiplus_graphicsgetdc _gdiplus_graphicsgetsmoothingmode _gdiplus_graphicsmeasurestring "
    "_gdiplus_graphicsreleasedc _gdiplus_graphicssetsmoothingmode _gdiplus_graphicssettransform "
    "_gdiplus_imagedispose _gdiplus_imagegetflags _gdiplus_imagegetgraphicscontext _gdiplus_imagegetheight "
    "_gdiplus_imagegethorizontalresolution _gdiplus_imagegetpixelformat _gdiplus_imagegetrawformat "
    "_gdiplus_imagegettype _gdiplus_imagegetverticalresolution _gdiplus_imagegetwidth _gdiplus_imageloadfromfile "
    "_gdiplus_imagesavetofile _gdiplus_imagesavetofileex _gdiplus_matrixcreate _gdiplus_matrixdispose "
    "_gdiplus_matrixrotate _gdiplus_matrixscale _gdiplus_matrixtranslate _gdiplus_paramadd _gdiplus_paraminit "
    "_gdiplus_pencreate _gdiplus_pendispose _gdiplus_pengetalignment _gdiplus_pengetcolor _gdiplus_pengetcustomendcap "
    "_gdiplus_pengetdashcap _gdiplus_pengetdashstyle _gdiplus_pengetendcap _gdiplus_pengetwidth "
    "_gdiplus_pensetalignment _gdiplus_pensetcolor _gdiplus_pensetcustomendcap _gdiplus_pensetdashcap "
    "_gdiplus_pensetdashstyle _gdiplus_pensetendcap _gdiplus_pensetwidth _gdiplus_rectfcreate _gdiplus_shutdown "
    "_gdiplus_startup _gdiplus_stringformatcreate _gdiplus_stringformatdispose _gdiplus_stringformatsetalign" 
    "_guictrlavi_close _guictrlavi_create _guictrlavi_destroy _guictrlavi_isplaying _guictrlavi_open "
    "_guictrlavi_openex _guictrlavi_play _guictrlavi_seek _guictrlavi_show _guictrlavi_stop _guictrlbutton_click "
    "_guictrlbutton_create _guictrlbutton_destroy _guictrlbutton_enable _guictrlbutton_getcheck "
    "_guictrlbutton_getfocus _guictrlbutton_getidealsize _guictrlbutton_getimage _guictrlbutton_getimagelist "
    "_guictrlbutton_getnote _guictrlbutton_getnotelength _guictrlbutton_getsplitinfo _guictrlbutton_getstate "
    "_guictrlbutton_gettext _guictrlbutton_gettextmargin _guictrlbutton_setcheck _guictrlbutton_setdontclick "
    "_guictrlbutton_setfocus _guictrlbutton_setimage _guictrlbutton_setimagelist _guictrlbutton_setnote "
    "_guictrlbutton_setshield _guictrlbutton_setsize _guictrlbutton_setsplitinfo _guictrlbutton_setstate "
    "_guictrlbutton_setstyle _guictrlbutton_settext _guictrlbutton_settextmargin _guictrlbutton_show "
    "_guictrlcombobox_adddir _guictrlcombobox_addstring _guictrlcombobox_autocomplete "
    "_guictrlcombobox_beginupdate _guictrlcombobox_create _guictrlcombobox_deletestring "
    "_guictrlcombobox_destroy _guictrlcombobox_endupdate _guictrlcombobox_findstring "
    "_guictrlcombobox_findstringexact _guictrlcombobox_getcomboboxinfo _guictrlcombobox_getcount "
    "_guictrlcombobox_getcuebanner _guictrlcombobox_getcursel _guictrlcombobox_getdroppedcontrolrect "
    "_guictrlcombobox_getdroppedcontrolrectex _guictrlcombobox_getdroppedstate _guictrlcombobox_getdroppedwidth "
    "_guictrlcombobox_geteditsel _guictrlcombobox_getedittext _guictrlcombobox_getextendedui "
    "_guictrlcombobox_gethorizontalextent _guictrlcombobox_getitemheight _guictrlcombobox_getlbtext "
    "_guictrlcombobox_getlbtextlen _guictrlcombobox_getlist _guictrlcombobox_getlistarray "
    "_guictrlcombobox_getlocale _guictrlcombobox_getlocalecountry _guictrlcombobox_getlocalelang "
    "_guictrlcombobox_getlocaleprimlang _guictrlcombobox_getlocalesublang _guictrlcombobox_getminvisible "
    "_guictrlcombobox_gettopindex _guictrlcombobox_initstorage _guictrlcombobox_insertstring "
    "_guictrlcombobox_limittext _guictrlcombobox_replaceeditsel _guictrlcombobox_resetcontent "
    "_guictrlcombobox_selectstring _guictrlcombobox_setcuebanner _guictrlcombobox_setcursel "
    "_guictrlcombobox_setdroppedwidth _guictrlcombobox_seteditsel _guictrlcombobox_setedittext "
    "_guictrlcombobox_setextendedui _guictrlcombobox_sethorizontalextent _guictrlcombobox_setitemheight "
    "_guictrlcombobox_setminvisible _guictrlcombobox_settopindex _guictrlcombobox_showdropdown "
    "_guictrlcomboboxex_adddir _guictrlcomboboxex_addstring _guictrlcomboboxex_beginupdate "
    "_guictrlcomboboxex_create _guictrlcomboboxex_createsolidbitmap _guictrlcomboboxex_deletestring "
    "_guictrlcomboboxex_destroy _guictrlcomboboxex_endupdate _guictrlcomboboxex_findstringexact "
    "_guictrlcomboboxex_getcomboboxinfo _guictrlcomboboxex_getcombocontrol _guictrlcomboboxex_getcount "
    "_guictrlcomboboxex_getcursel _guictrlcomboboxex_getdroppedcontrolrect _guictrlcomboboxex_getdroppedcontrolrectex "
    "_guictrlcomboboxex_getdroppedstate _guictrlcomboboxex_getdroppedwidth _guictrlcomboboxex_geteditcontrol "
    "_guictrlcomboboxex_geteditsel _guictrlcomboboxex_getedittext _guictrlcomboboxex_getextendedstyle "
    "_guictrlcomboboxex_getextendedui _guictrlcomboboxex_getimagelist _guictrlcomboboxex_getitem "
    "_guictrlcomboboxex_getitemex _guictrlcomboboxex_getitemheight _guictrlcomboboxex_getitemimage "
    "_guictrlcomboboxex_getitemindent _guictrlcomboboxex_getitemoverlayimage _guictrlcomboboxex_getitemparam "
    "_guictrlcomboboxex_getitemselectedimage _guictrlcomboboxex_getitemtext _guictrlcomboboxex_getitemtextlen "
    "_guictrlcomboboxex_getlist _guictrlcomboboxex_getlistarray _guictrlcomboboxex_getlocale "
    "_guictrlcomboboxex_getlocalecountry _guictrlcomboboxex_getlocalelang _guictrlcomboboxex_getlocaleprimlang "
    "_guictrlcomboboxex_getlocalesublang _guictrlcomboboxex_getminvisible _guictrlcomboboxex_gettopindex "
    "_guictrlcomboboxex_getunicode _guictrlcomboboxex_initstorage _guictrlcomboboxex_insertstring "
    "_guictrlcomboboxex_limittext _guictrlcomboboxex_replaceeditsel _guictrlcomboboxex_resetcontent "
    "_guictrlcomboboxex_setcursel _guictrlcomboboxex_setdroppedwidth _guictrlcomboboxex_seteditsel "
    "_guictrlcomboboxex_setedittext _guictrlcomboboxex_setextendedstyle _guictrlcomboboxex_setextendedui "
    "_guictrlcomboboxex_setimagelist _guictrlcomboboxex_setitem _guictrlcomboboxex_setitemex "
    "_guictrlcomboboxex_setitemheight _guictrlcomboboxex_setitemimage _guictrlcomboboxex_setitemindent "
    "_guictrlcomboboxex_setitemoverlayimage _guictrlcomboboxex_setitemparam _guictrlcomboboxex_setitemselectedimage "
    "_guictrlcomboboxex_setminvisible _guictrlcomboboxex_settopindex _guictrlcomboboxex_setunicode "
    "_guictrlcomboboxex_showdropdown _guictrldtp_create _guictrldtp_destroy _guictrldtp_getmccolor "
    "_guictrldtp_getmcfont _guictrldtp_getmonthcal _guictrldtp_getrange _guictrldtp_getrangeex "
    "_guictrldtp_getsystemtime _guictrldtp_getsystemtimeex _guictrldtp_setformat _guictrldtp_setmccolor "
    "_guictrldtp_setmcfont _guictrldtp_setrange _guictrldtp_setrangeex _guictrldtp_setsystemtime "
    "_guictrldtp_setsystemtimeex _guictrledit_appendtext _guictrledit_beginupdate _guictrledit_canundo "
    "_guictrledit_charfrompos _guictrledit_create _guictrledit_destroy _guictrledit_emptyundobuffer "
    "_guictrledit_endupdate _guictrledit_find _guictrledit_fmtlines _guictrledit_getcuebanner "
    "_guictrledit_getfirstvisibleline _guictrledit_getlimittext _guictrledit_getline _guictrledit_getlinecount "
    "_guictrledit_getmargins _guictrledit_getmodify _guictrledit_getpasswordchar _guictrledit_getrect "
    "_guictrledit_getrectex _guictrledit_getsel _guictrledit_gettext _guictrledit_gettextlen "
    "_guictrledit_hideballoontip _guictrledit_inserttext _guictrledit_linefromchar _guictrledit_lineindex "
    "_guictrledit_linelength _guictrledit_linescroll _guictrledit_posfromchar _guictrledit_replacesel "
    "_guictrledit_scroll _guictrledit_setcuebanner _guictrledit_setlimittext _guictrledit_setmargins "
    "_guictrledit_setmodify _guictrledit_setpadding _guictrledit_setpasswordchar _guictrledit_setreadonly "
    "_guictrledit_setrect _guictrledit_setrectex _guictrledit_setrectnp _guictrledit_setrectnpex "
    "_guictrledit_setsel _guictrledit_settabstops _guictrledit_settext _guictrledit_showballoontip "
    "_guictrledit_undo _guictrlheader_additem _guictrlheader_clearfilter _guictrlheader_clearfilterall "
    "_guictrlheader_create _guictrlheader_createdragimage _guictrlheader_deleteitem _guictrlheader_destroy "
    "_guictrlheader_editfilter _guictrlheader_getbitmapmargin _guictrlheader_getfiltertext "
    "_guictrlheader_getimagelist _guictrlheader_getitem _guictrlheader_getitemalign _guictrlheader_getitembitmap "
    "_guictrlheader_getitemcount _guictrlheader_getitemdisplay _guictrlheader_getitemflags "
    "_guictrlheader_getitemformat _guictrlheader_getitemimage _guictrlheader_getitemorder "
    "_guictrlheader_getitemparam _guictrlheader_getitemrect _guictrlheader_getitemrectex _guictrlheader_getitemtext "
    "_guictrlheader_getitemwidth _guictrlheader_getorderarray _guictrlheader_getunicodeformat _guictrlheader_hittest "
    "_guictrlheader_insertitem _guictrlheader_layout _guictrlheader_ordertoindex _guictrlheader_setbitmapmargin "
    "_guictrlheader_setfilterchangetimeout _guictrlheader_sethotdivider _guictrlheader_setimagelist "
    "_guictrlheader_setitem _guictrlheader_setitemalign _guictrlheader_setitembitmap _guictrlheader_setitemdisplay "
    "_guictrlheader_setitemflags _guictrlheader_setitemformat _guictrlheader_setitemimage _guictrlheader_setitemorder "
    "_guictrlheader_setitemparam _guictrlheader_setitemtext _guictrlheader_setitemwidth _guictrlheader_setorderarray "
    "_guictrlheader_setunicodeformat _guictrlipaddress_clearaddress _guictrlipaddress_create _guictrlipaddress_destroy "
    "_guictrlipaddress_get _guictrlipaddress_getarray _guictrlipaddress_getex _guictrlipaddress_isblank "
    "_guictrlipaddress_set _guictrlipaddress_setarray _guictrlipaddress_setex _guictrlipaddress_setfocus "
    "_guictrlipaddress_setfont _guictrlipaddress_setrange _guictrlipaddress_showhide _guictrllistbox_addfile "
    "_guictrllistbox_addstring _guictrllistbox_beginupdate _guictrllistbox_clickitem _guictrllistbox_create "
    "_guictrllistbox_deletestring _guictrllistbox_destroy _guictrllistbox_dir _guictrllistbox_endupdate "
    "_guictrllistbox_findintext _guictrllistbox_findstring _guictrllistbox_getanchorindex "
    "_guictrllistbox_getcaretindex _guictrllistbox_getcount _guictrllistbox_getcursel "
    "_guictrllistbox_gethorizontalextent _guictrllistbox_getitemdata _guictrllistbox_getitemheight "
    "_guictrllistbox_getitemrect _guictrllistbox_getitemrectex _guictrllistbox_getlistboxinfo "
    "_guictrllistbox_getlocale _guictrllistbox_getlocalecountry _guictrllistbox_getlocalelang "
    "_guictrllistbox_getlocaleprimlang _guictrllistbox_getlocalesublang _guictrllistbox_getsel "
    "_guictrllistbox_getselcount _guictrllistbox_getselitems _guictrllistbox_getselitemstext "
    "_guictrllistbox_gettext _guictrllistbox_gettextlen _guictrllistbox_gettopindex _guictrllistbox_initstorage "
    "_guictrllistbox_insertstring _guictrllistbox_itemfrompoint _guictrllistbox_replacestring "
    "_guictrllistbox_resetcontent _guictrllistbox_selectstring _guictrllistbox_selitemrange "
    "_guictrllistbox_selitemrangeex _guictrllistbox_setanchorindex _guictrllistbox_setcaretindex "
    "_guictrllistbox_setcolumnwidth _guictrllistbox_setcursel _guictrllistbox_sethorizontalextent "
    "_guictrllistbox_setitemdata _guictrllistbox_setitemheight _guictrllistbox_setlocale _guictrllistbox_setsel "
    "_guictrllistbox_settabstops _guictrllistbox_settopindex _guictrllistbox_sort _guictrllistbox_swapstring "
    "_guictrllistbox_updatehscroll _guictrllistview_addarray _guictrllistview_addcolumn _guictrllistview_additem "
    "_guictrllistview_addsubitem _guictrllistview_approximateviewheight _guictrllistview_approximateviewrect "
    "_guictrllistview_approximateviewwidth _guictrllistview_arrange _guictrllistview_beginupdate "
    "_guictrllistview_canceleditlabel _guictrllistview_clickitem _guictrllistview_copyitems "
    "_guictrllistview_create _guictrllistview_createdragimage _guictrllistview_createsolidbitmap "
    "_guictrllistview_deleteallitems _guictrllistview_deletecolumn _guictrllistview_deleteitem "
    "_guictrllistview_deleteitemsselected _guictrllistview_destroy _guictrllistview_drawdragimage "
    "_guictrllistview_editlabel _guictrllistview_enablegroupview _guictrllistview_endupdate "
    "_guictrllistview_ensurevisible _guictrllistview_findintext _guictrllistview_finditem "
    "_guictrllistview_findnearest _guictrllistview_findparam _guictrllistview_findtext "
    "_guictrllistview_getbkcolor _guictrllistview_getbkimage _guictrllistview_getcallbackmask "
    "_guictrllistview_getcolumn _guictrllistview_getcolumncount _guictrllistview_getcolumnorder "
    "_guictrllistview_getcolumnorderarray _guictrllistview_getcolumnwidth _guictrllistview_getcounterpage "
    "_guictrllistview_geteditcontrol _guictrllistview_getextendedlistviewstyle _guictrllistview_getfocusedgroup "
    "_guictrllistview_getgroupcount _guictrllistview_getgroupinfo _guictrllistview_getgroupinfobyindex "
    "_guictrllistview_getgrouprect _guictrllistview_getgroupviewenabled _guictrllistview_getheader "
    "_guictrllistview_gethotcursor _guictrllistview_gethotitem _guictrllistview_gethovertime "
    "_guictrllistview_getimagelist _guictrllistview_getisearchstring _guictrllistview_getitem "
    "_guictrllistview_getitemchecked _guictrllistview_getitemcount _guictrllistview_getitemcut "
    "_guictrllistview_getitemdrophilited _guictrllistview_getitemex _guictrllistview_getitemfocused "
    "_guictrllistview_getitemgroupid _guictrllistview_getitemimage _guictrllistview_getitemindent "
    "_guictrllistview_getitemparam _guictrllistview_getitemposition _guictrllistview_getitempositionx "
    "_guictrllistview_getitempositiony _guictrllistview_getitemrect _guictrllistview_getitemrectex "
    "_guictrllistview_getitemselected _guictrllistview_getitemspacing _guictrllistview_getitemspacingx "
    "_guictrllistview_getitemspacingy _guictrllistview_getitemstate _guictrllistview_getitemstateimage "
    "_guictrllistview_getitemtext _guictrllistview_getitemtextarray _guictrllistview_getitemtextstring "
    "_guictrllistview_getnextitem _guictrllistview_getnumberofworkareas _guictrllistview_getorigin "
    "_guictrllistview_getoriginx _guictrllistview_getoriginy _guictrllistview_getoutlinecolor "
    "_guictrllistview_getselectedcolumn _guictrllistview_getselectedcount _guictrllistview_getselectedindices "
    "_guictrllistview_getselectionmark _guictrllistview_getstringwidth _guictrllistview_getsubitemrect "
    "_guictrllistview_gettextbkcolor _guictrllistview_gettextcolor _guictrllistview_gettooltips "
    "_guictrllistview_gettopindex _guictrllistview_getunicodeformat _guictrllistview_getview "
    "_guictrllistview_getviewdetails _guictrllistview_getviewlarge _guictrllistview_getviewlist "
    "_guictrllistview_getviewrect _guictrllistview_getviewsmall _guictrllistview_getviewtile "
    "_guictrllistview_hidecolumn _guictrllistview_hittest _guictrllistview_insertcolumn "
    "_guictrllistview_insertgroup _guictrllistview_insertitem _guictrllistview_justifycolumn "
    "_guictrllistview_mapidtoindex _guictrllistview_mapindextoid _guictrllistview_redrawitems "
    "_guictrllistview_registersortcallback _guictrllistview_removeallgroups _guictrllistview_removegroup "
    "_guictrllistview_scroll _guictrllistview_setbkcolor _guictrllistview_setbkhbitmap _guictrllistview_setbkimage "
    "_guictrllistview_setcallbackmask _guictrllistview_setcolumn _guictrllistview_setcolumnorder "
    "_guictrllistview_setcolumnorderarray _guictrllistview_setcolumnwidth _guictrllistview_setextendedlistviewstyle "
    "_guictrllistview_setgroupinfo _guictrllistview_sethotitem _guictrllistview_sethovertime "
    "_guictrllistview_seticonspacing _guictrllistview_setimagelist _guictrllistview_setitem "
    "_guictrllistview_setitemchecked _guictrllistview_setitemcount _guictrllistview_setitemcut "
    "_guictrllistview_setitemdrophilited _guictrllistview_setitemex _guictrllistview_setitemfocused "
    "_guictrllistview_setitemgroupid _guictrllistview_setitemimage _guictrllistview_setitemindent "
    "_guictrllistview_setitemparam _guictrllistview_setitemposition _guictrllistview_setitemposition32 "
    "_guictrllistview_setitemselected _guictrllistview_setitemstate _guictrllistview_setitemstateimage "
    "_guictrllistview_setitemtext _guictrllistview_setoutlinecolor _guictrllistview_setselectedcolumn "
    "_guictrllistview_setselectionmark _guictrllistview_settextbkcolor _guictrllistview_settextcolor "
    "_guictrllistview_settooltips _guictrllistview_setunicodeformat _guictrllistview_setview "
    "_guictrllistview_setworkareas _guictrllistview_simplesort _guictrllistview_sortitems "
    "_guictrllistview_subitemhittest _guictrllistview_unregistersortcallback _guictrlmenu_addmenuitem "
    "_guictrlmenu_appendmenu _guictrlmenu_calculatepopupwindowposition _guictrlmenu_checkmenuitem "
    "_guictrlmenu_checkradioitem _guictrlmenu_createmenu _guictrlmenu_createpopup _guictrlmenu_deletemenu "
    "_guictrlmenu_destroymenu _guictrlmenu_drawmenubar _guictrlmenu_enablemenuitem _guictrlmenu_finditem "
    "_guictrlmenu_findparent _guictrlmenu_getitembmp _guictrlmenu_getitembmpchecked "
    "_guictrlmenu_getitembmpunchecked _guictrlmenu_getitemchecked _guictrlmenu_getitemcount "
    "_guictrlmenu_getitemdata _guictrlmenu_getitemdefault _guictrlmenu_getitemdisabled "
    "_guictrlmenu_getitemenabled _guictrlmenu_getitemgrayed _guictrlmenu_getitemhighlighted "
    "_guictrlmenu_getitemid _guictrlmenu_getiteminfo _guictrlmenu_getitemrect _guictrlmenu_getitemrectex "
    "_guictrlmenu_getitemstate _guictrlmenu_getitemstateex _guictrlmenu_getitemsubmenu _guictrlmenu_getitemtext "
    "_guictrlmenu_getitemtype _guictrlmenu_getmenu _guictrlmenu_getmenubackground _guictrlmenu_getmenubarinfo "
    "_guictrlmenu_getmenucontexthelpid _guictrlmenu_getmenudata _guictrlmenu_getmenudefaultitem "
    "_guictrlmenu_getmenuheight _guictrlmenu_getmenuinfo _guictrlmenu_getmenustyle _guictrlmenu_getsystemmenu "
    "_guictrlmenu_insertmenuitem _guictrlmenu_insertmenuitemex _guictrlmenu_ismenu _guictrlmenu_loadmenu "
    "_guictrlmenu_mapaccelerator _guictrlmenu_menuitemfrompoint _guictrlmenu_removemenu "
    "_guictrlmenu_setitembitmaps _guictrlmenu_setitembmp _guictrlmenu_setitembmpchecked "
    "_guictrlmenu_setitembmpunchecked _guictrlmenu_setitemchecked _guictrlmenu_setitemdata "
    "_guictrlmenu_setitemdefault _guictrlmenu_setitemdisabled _guictrlmenu_setitemenabled "
    "_guictrlmenu_setitemgrayed _guictrlmenu_setitemhighlighted _guictrlmenu_setitemid _guictrlmenu_setiteminfo "
    "_guictrlmenu_setitemstate _guictrlmenu_setitemsubmenu _guictrlmenu_setitemtext _guictrlmenu_setitemtype "
    "_guictrlmenu_setmenu _guictrlmenu_setmenubackground _guictrlmenu_setmenucontexthelpid _guictrlmenu_setmenudata "
    "_guictrlmenu_setmenudefaultitem _guictrlmenu_setmenuheight _guictrlmenu_setmenuinfo _guictrlmenu_setmenustyle "
    "_guictrlmenu_trackpopupmenu _guictrlmonthcal_create _guictrlmonthcal_destroy _guictrlmonthcal_getcalendarborder "
    "_guictrlmonthcal_getcalendarcount _guictrlmonthcal_getcolor _guictrlmonthcal_getcolorarray "
    "_guictrlmonthcal_getcursel _guictrlmonthcal_getcurselstr _guictrlmonthcal_getfirstdow "
    "_guictrlmonthcal_getfirstdowstr _guictrlmonthcal_getmaxselcount _guictrlmonthcal_getmaxtodaywidth "
    "_guictrlmonthcal_getminreqheight _guictrlmonthcal_getminreqrect _guictrlmonthcal_getminreqrectarray "
    "_guictrlmonthcal_getminreqwidth _guictrlmonthcal_getmonthdelta _guictrlmonthcal_getmonthrange "
    "_guictrlmonthcal_getmonthrangemax _guictrlmonthcal_getmonthrangemaxstr _guictrlmonthcal_getmonthrangemin "
    "_guictrlmonthcal_getmonthrangeminstr _guictrlmonthcal_getmonthrangespan _guictrlmonthcal_getrange "
    "_guictrlmonthcal_getrangemax _guictrlmonthcal_getrangemaxstr _guictrlmonthcal_getrangemin "
    "_guictrlmonthcal_getrangeminstr _guictrlmonthcal_getselrange _guictrlmonthcal_getselrangemax "
    "_guictrlmonthcal_getselrangemaxstr _guictrlmonthcal_getselrangemin _guictrlmonthcal_getselrangeminstr "
    "_guictrlmonthcal_gettoday _guictrlmonthcal_gettodaystr _guictrlmonthcal_getunicodeformat "
    "_guictrlmonthcal_hittest _guictrlmonthcal_setcalendarborder _guictrlmonthcal_setcolor "
    "_guictrlmonthcal_setcursel _guictrlmonthcal_setdaystate _guictrlmonthcal_setfirstdow "
    "_guictrlmonthcal_setmaxselcount _guictrlmonthcal_setmonthdelta _guictrlmonthcal_setrange "
    "_guictrlmonthcal_setselrange _guictrlmonthcal_settoday _guictrlmonthcal_setunicodeformat "
    "_guictrlrebar_addband _guictrlrebar_addtoolbarband _guictrlrebar_begindrag _guictrlrebar_create "
    "_guictrlrebar_deleteband _guictrlrebar_destroy _guictrlrebar_dragmove _guictrlrebar_enddrag "
    "_guictrlrebar_getbandbackcolor _guictrlrebar_getbandborders _guictrlrebar_getbandbordersex "
    "_guictrlrebar_getbandchildhandle _guictrlrebar_getbandchildsize _guictrlrebar_getbandcount "
    "_guictrlrebar_getbandforecolor _guictrlrebar_getbandheadersize _guictrlrebar_getbandid "
    "_guictrlrebar_getbandidealsize _guictrlrebar_getbandlength _guictrlrebar_getbandlparam "
    "_guictrlrebar_getbandmargins _guictrlrebar_getbandmarginsex _guictrlrebar_getbandrect "
    "_guictrlrebar_getbandrectex _guictrlrebar_getbandstyle _guictrlrebar_getbandstylebreak "
    "_guictrlrebar_getbandstylechildedge _guictrlrebar_getbandstylefixedbmp "
    "_guictrlrebar_getbandstylefixedsize _guictrlrebar_getbandstylegripperalways "
    "_guictrlrebar_getbandstylehidden _guictrlrebar_getbandstylehidetitle _guictrlrebar_getbandstylenogripper "
    "_guictrlrebar_getbandstyletopalign _guictrlrebar_getbandstyleusechevron "
    "_guictrlrebar_getbandstylevariableheight _guictrlrebar_getbandtext _guictrlrebar_getbarheight "
    "_guictrlrebar_getbarinfo _guictrlrebar_getbkcolor _guictrlrebar_getcolorscheme _guictrlrebar_getrowcount "
    "_guictrlrebar_getrowheight _guictrlrebar_gettextcolor _guictrlrebar_gettooltips "
    "_guictrlrebar_getunicodeformat _guictrlrebar_hittest _guictrlrebar_idtoindex _guictrlrebar_maximizeband "
    "_guictrlrebar_minimizeband _guictrlrebar_moveband _guictrlrebar_setbandbackcolor "
    "_guictrlrebar_setbandforecolor _guictrlrebar_setbandheadersize _guictrlrebar_setbandid "
    "_guictrlrebar_setbandidealsize _guictrlrebar_setbandlength _guictrlrebar_setbandlparam "
    "_guictrlrebar_setbandstyle _guictrlrebar_setbandstylebreak _guictrlrebar_setbandstylechildedge "
    "_guictrlrebar_setbandstylefixedbmp _guictrlrebar_setbandstylefixedsize "
    "_guictrlrebar_setbandstylegripperalways _guictrlrebar_setbandstylehidden "
    "_guictrlrebar_setbandstylehidetitle _guictrlrebar_setbandstylenogripper "
    "_guictrlrebar_setbandstyletopalign _guictrlrebar_setbandstyleusechevron "
    "_guictrlrebar_setbandstylevariableheight _guictrlrebar_setbandtext _guictrlrebar_setbarinfo "
    "_guictrlrebar_setbkcolor _guictrlrebar_setcolorscheme _guictrlrebar_settextcolor "
    "_guictrlrebar_settooltips _guictrlrebar_setunicodeformat _guictrlrebar_showband "
    "_guictrlrichedit_appendtext _guictrlrichedit_autodetecturl _guictrlrichedit_canpaste "
    "_guictrlrichedit_canpastespecial _guictrlrichedit_canredo _guictrlrichedit_canundo "
    "_guictrlrichedit_changefontsize _guictrlrichedit_copy _guictrlrichedit_create _guictrlrichedit_cut "
    "_guictrlrichedit_deselect _guictrlrichedit_destroy _guictrlrichedit_emptyundobuffer "
    "_guictrlrichedit_findtext _guictrlrichedit_findtextinrange _guictrlrichedit_getbkcolor "
    "_guictrlrichedit_getcharattributes _guictrlrichedit_getcharbkcolor _guictrlrichedit_getcharcolor "
    "_guictrlrichedit_getcharposfromxy _guictrlrichedit_getcharposofnextword "
    "_guictrlrichedit_getcharposofpreviousword _guictrlrichedit_getcharwordbreakinfo "
    "_guictrlrichedit_getfirstcharposonline _guictrlrichedit_getfont _guictrlrichedit_getlinecount "
    "_guictrlrichedit_getlinelength _guictrlrichedit_getlinenumberfromcharpos _guictrlrichedit_getnextredo "
    "_guictrlrichedit_getnextundo _guictrlrichedit_getnumberoffirstvisibleline "
    "_guictrlrichedit_getparaalignment _guictrlrichedit_getparaattributes _guictrlrichedit_getparaborder "
    "_guictrlrichedit_getparaindents _guictrlrichedit_getparanumbering _guictrlrichedit_getparashading "
    "_guictrlrichedit_getparaspacing _guictrlrichedit_getparatabstops _guictrlrichedit_getpasswordchar "
    "_guictrlrichedit_getrect _guictrlrichedit_getscrollpos _guictrlrichedit_getsel _guictrlrichedit_getselaa "
    "_guictrlrichedit_getseltext _guictrlrichedit_getspaceunit _guictrlrichedit_gettext "
    "_guictrlrichedit_gettextinline _guictrlrichedit_gettextinrange _guictrlrichedit_gettextlength "
    "_guictrlrichedit_getversion _guictrlrichedit_getxyfromcharpos _guictrlrichedit_getzoom "
    "_guictrlrichedit_gotocharpos _guictrlrichedit_hideselection _guictrlrichedit_inserttext "
    "_guictrlrichedit_ismodified _guictrlrichedit_istextselected _guictrlrichedit_paste "
    "_guictrlrichedit_pastespecial _guictrlrichedit_pauseredraw _guictrlrichedit_redo "
    "_guictrlrichedit_replacetext _guictrlrichedit_resumeredraw _guictrlrichedit_scrolllineorpage "
    "_guictrlrichedit_scrolllines _guictrlrichedit_scrolltocaret _guictrlrichedit_setbkcolor "
    "_guictrlrichedit_setcharattributes _guictrlrichedit_setcharbkcolor _guictrlrichedit_setcharcolor "
    "_guictrlrichedit_seteventmask _guictrlrichedit_setfont _guictrlrichedit_setlimitontext "
    "_guictrlrichedit_setmodified _guictrlrichedit_setparaalignment _guictrlrichedit_setparaattributes "
    "_guictrlrichedit_setparaborder _guictrlrichedit_setparaindents _guictrlrichedit_setparanumbering "
    "_guictrlrichedit_setparashading _guictrlrichedit_setparaspacing _guictrlrichedit_setparatabstops "
    "_guictrlrichedit_setpasswordchar _guictrlrichedit_setreadonly _guictrlrichedit_setrect "
    "_guictrlrichedit_setscrollpos _guictrlrichedit_setsel _guictrlrichedit_setspaceunit "
    "_guictrlrichedit_settabstops _guictrlrichedit_settext _guictrlrichedit_setundolimit _guictrlrichedit_setzoom "
    "_guictrlrichedit_streamfromfile _guictrlrichedit_streamfromvar _guictrlrichedit_streamtofile "
    "_guictrlrichedit_streamtovar _guictrlrichedit_undo _guictrlslider_clearsel _guictrlslider_cleartics "
    "_guictrlslider_create _guictrlslider_destroy _guictrlslider_getbuddy _guictrlslider_getchannelrect "
    "_guictrlslider_getchannelrectex _guictrlslider_getlinesize _guictrlslider_getlogicaltics "
    "_guictrlslider_getnumtics _guictrlslider_getpagesize _guictrlslider_getpos _guictrlslider_getrange "
    "_guictrlslider_getrangemax _guictrlslider_getrangemin _guictrlslider_getsel _guictrlslider_getselend "
    "_guictrlslider_getselstart _guictrlslider_getthumblength _guictrlslider_getthumbrect "
    "_guictrlslider_getthumbrectex _guictrlslider_gettic _guictrlslider_getticpos _guictrlslider_gettooltips "
    "_guictrlslider_getunicodeformat _guictrlslider_setbuddy _guictrlslider_setlinesize _guictrlslider_setpagesize "
    "_guictrlslider_setpos _guictrlslider_setrange _guictrlslider_setrangemax _guictrlslider_setrangemin "
    "_guictrlslider_setsel _guictrlslider_setselend _guictrlslider_setselstart _guictrlslider_setthumblength "
    "_guictrlslider_settic _guictrlslider_setticfreq _guictrlslider_settipside _guictrlslider_settooltips "
    "_guictrlslider_setunicodeformat _guictrlstatusbar_create _guictrlstatusbar_destroy "
    "_guictrlstatusbar_embedcontrol _guictrlstatusbar_getborders _guictrlstatusbar_getbordershorz "
    "_guictrlstatusbar_getbordersrect _guictrlstatusbar_getbordersvert _guictrlstatusbar_getcount "
    "_guictrlstatusbar_getheight _guictrlstatusbar_geticon _guictrlstatusbar_getparts _guictrlstatusbar_getrect "
    "_guictrlstatusbar_getrectex _guictrlstatusbar_gettext _guictrlstatusbar_gettextflags _guictrlstatusbar_gettextlength "
    "_guictrlstatusbar_gettextlengthex _guictrlstatusbar_gettiptext _guictrlstatusbar_getunicodeformat "
    "_guictrlstatusbar_getwidth _guictrlstatusbar_issimple _guictrlstatusbar_resize _guictrlstatusbar_setbkcolor "
    "_guictrlstatusbar_seticon _guictrlstatusbar_setminheight _guictrlstatusbar_setparts "
    "_guictrlstatusbar_setsimple _guictrlstatusbar_settext _guictrlstatusbar_settiptext "
    "_guictrlstatusbar_setunicodeformat _guictrlstatusbar_showhide "
    "_guictrltab_activatetab _guictrltab_clicktab _guictrltab_create _guictrltab_deleteallitems "
    "_guictrltab_deleteitem _guictrltab_deselectall _guictrltab_destroy _guictrltab_findtab "
    "_guictrltab_getcurfocus _guictrltab_getcursel _guictrltab_getdisplayrect _guictrltab_getdisplayrectex "
    "_guictrltab_getextendedstyle _guictrltab_getimagelist _guictrltab_getitem _guictrltab_getitemcount "
    "_guictrltab_getitemimage _guictrltab_getitemparam _guictrltab_getitemrect _guictrltab_getitemrectex "
    "_guictrltab_getitemstate _guictrltab_getitemtext _guictrltab_getrowcount _guictrltab_gettooltips "
    "_guictrltab_getunicodeformat _guictrltab_highlightitem _guictrltab_hittest _guictrltab_insertitem "
    "_guictrltab_removeimage _guictrltab_setcurfocus _guictrltab_setcursel _guictrltab_setextendedstyle "
    "_guictrltab_setimagelist _guictrltab_setitem _guictrltab_setitemimage _guictrltab_setitemparam "
    "_guictrltab_setitemsize _guictrltab_setitemstate _guictrltab_setitemtext _guictrltab_setmintabwidth "
    "_guictrltab_setpadding _guictrltab_settooltips _guictrltab_setunicodeformat "
    "_guictrltoolbar_addbitmap _guictrltoolbar_addbutton _guictrltoolbar_addbuttonsep _guictrltoolbar_addstring "
    "_guictrltoolbar_buttoncount _guictrltoolbar_checkbutton _guictrltoolbar_clickaccel "
    "_guictrltoolbar_clickbutton _guictrltoolbar_clickindex _guictrltoolbar_commandtoindex _guictrltoolbar_create "
    "_guictrltoolbar_customize _guictrltoolbar_deletebutton _guictrltoolbar_destroy _guictrltoolbar_enablebutton "
    "_guictrltoolbar_findtoolbar _guictrltoolbar_getanchorhighlight _guictrltoolbar_getbitmapflags "
    "_guictrltoolbar_getbuttonbitmap _guictrltoolbar_getbuttoninfo _guictrltoolbar_getbuttoninfoex "
    "_guictrltoolbar_getbuttonparam _guictrltoolbar_getbuttonrect _guictrltoolbar_getbuttonrectex "
    "_guictrltoolbar_getbuttonsize _guictrltoolbar_getbuttonstate _guictrltoolbar_getbuttonstyle "
    "_guictrltoolbar_getbuttontext _guictrltoolbar_getcolorscheme _guictrltoolbar_getdisabledimagelist "
    "_guictrltoolbar_getextendedstyle _guictrltoolbar_gethotimagelist _guictrltoolbar_gethotitem "
    "_guictrltoolbar_getimagelist _guictrltoolbar_getinsertmark _guictrltoolbar_getinsertmarkcolor "
    "_guictrltoolbar_getmaxsize _guictrltoolbar_getmetrics _guictrltoolbar_getpadding _guictrltoolbar_getrows "
    "_guictrltoolbar_getstring _guictrltoolbar_getstyle _guictrltoolbar_getstylealtdrag "
    "_guictrltoolbar_getstylecustomerase _guictrltoolbar_getstyleflat _guictrltoolbar_getstylelist "
    "_guictrltoolbar_getstyleregisterdrop _guictrltoolbar_getstyletooltips _guictrltoolbar_getstyletransparent "
    "_guictrltoolbar_getstylewrapable _guictrltoolbar_gettextrows _guictrltoolbar_gettooltips "
    "_guictrltoolbar_getunicodeformat _guictrltoolbar_hidebutton _guictrltoolbar_highlightbutton "
    "_guictrltoolbar_hittest _guictrltoolbar_indextocommand _guictrltoolbar_insertbutton "
    "_guictrltoolbar_insertmarkhittest _guictrltoolbar_isbuttonchecked _guictrltoolbar_isbuttonenabled "
    "_guictrltoolbar_isbuttonhidden _guictrltoolbar_isbuttonhighlighted _guictrltoolbar_isbuttonindeterminate "
    "_guictrltoolbar_isbuttonpressed _guictrltoolbar_loadbitmap _guictrltoolbar_loadimages "
    "_guictrltoolbar_mapaccelerator _guictrltoolbar_movebutton _guictrltoolbar_pressbutton "
    "_guictrltoolbar_setanchorhighlight _guictrltoolbar_setbitmapsize _guictrltoolbar_setbuttonbitmap "
    "_guictrltoolbar_setbuttoninfo _guictrltoolbar_setbuttoninfoex _guictrltoolbar_setbuttonparam "
    "_guictrltoolbar_setbuttonsize _guictrltoolbar_setbuttonstate _guictrltoolbar_setbuttonstyle "
    "_guictrltoolbar_setbuttontext _guictrltoolbar_setbuttonwidth _guictrltoolbar_setcmdid "
    "_guictrltoolbar_setcolorscheme _guictrltoolbar_setdisabledimagelist _guictrltoolbar_setdrawtextflags "
    "_guictrltoolbar_setextendedstyle _guictrltoolbar_sethotimagelist _guictrltoolbar_sethotitem "
    "_guictrltoolbar_setimagelist _guictrltoolbar_setindent _guictrltoolbar_setindeterminate "
    "_guictrltoolbar_setinsertmark _guictrltoolbar_setinsertmarkcolor _guictrltoolbar_setmaxtextrows "
    "_guictrltoolbar_setmetrics _guictrltoolbar_setpadding _guictrltoolbar_setparent _guictrltoolbar_setrows "
    "_guictrltoolbar_setstyle _guictrltoolbar_setstylealtdrag _guictrltoolbar_setstylecustomerase "
    "_guictrltoolbar_setstyleflat _guictrltoolbar_setstylelist _guictrltoolbar_setstyleregisterdrop "
    "_guictrltoolbar_setstyletooltips _guictrltoolbar_setstyletransparent _guictrltoolbar_setstylewrapable "
    "_guictrltoolbar_settooltips _guictrltoolbar_setunicodeformat _guictrltoolbar_setwindowtheme "
    "_guictrltreeview_add _guictrltreeview_addchild _guictrltreeview_addchildfirst _guictrltreeview_addfirst "
    "_guictrltreeview_beginupdate _guictrltreeview_clickitem _guictrltreeview_create "
    "_guictrltreeview_createdragimage _guictrltreeview_createsolidbitmap _guictrltreeview_delete "
    "_guictrltreeview_deleteall _guictrltreeview_deletechildren _guictrltreeview_destroy "
    "_guictrltreeview_displayrect _guictrltreeview_displayrectex _guictrltreeview_edittext "
    "_guictrltreeview_endedit _guictrltreeview_endupdate _guictrltreeview_ensurevisible _guictrltreeview_expand "
    "_guictrltreeview_expandedonce _guictrltreeview_finditem _guictrltreeview_finditemex _guictrltreeview_getbkcolor "
    "_guictrltreeview_getbold _guictrltreeview_getchecked _guictrltreeview_getchildcount _guictrltreeview_getchildren "
    "_guictrltreeview_getcount _guictrltreeview_getcut _guictrltreeview_getdroptarget _guictrltreeview_geteditcontrol "
    "_guictrltreeview_getexpanded _guictrltreeview_getfirstchild _guictrltreeview_getfirstitem "
    "_guictrltreeview_getfirstvisible _guictrltreeview_getfocused _guictrltreeview_getheight "
    "_guictrltreeview_getimageindex _guictrltreeview_getimagelisticonhandle _guictrltreeview_getindent "
    "_guictrltreeview_getinsertmarkcolor _guictrltreeview_getisearchstring _guictrltreeview_getitembyindex "
    "_guictrltreeview_getitemhandle _guictrltreeview_getitemparam _guictrltreeview_getlastchild "
    "_guictrltreeview_getlastitem _guictrltreeview_getlinecolor _guictrltreeview_getnext "
    "_guictrltreeview_getnextchild _guictrltreeview_getnextsibling _guictrltreeview_getnextvisible "
    "_guictrltreeview_getnormalimagelist _guictrltreeview_getparenthandle _guictrltreeview_getparentparam "
    "_guictrltreeview_getprev _guictrltreeview_getprevchild _guictrltreeview_getprevsibling "
    "_guictrltreeview_getprevvisible _guictrltreeview_getscrolltime _guictrltreeview_getselected "
    "_guictrltreeview_getselectedimageindex _guictrltreeview_getselection _guictrltreeview_getsiblingcount "
    "_guictrltreeview_getstate _guictrltreeview_getstateimageindex _guictrltreeview_getstateimagelist "
    "_guictrltreeview_gettext _guictrltreeview_gettextcolor _guictrltreeview_gettooltips _guictrltreeview_gettree "
    "_guictrltreeview_getunicodeformat _guictrltreeview_getvisible _guictrltreeview_getvisiblecount "
    "_guictrltreeview_hittest _guictrltreeview_hittestex _guictrltreeview_hittestitem _guictrltreeview_index "
    "_guictrltreeview_insertitem _guictrltreeview_isfirstitem _guictrltreeview_isparent _guictrltreeview_level "
    "_guictrltreeview_selectitem _guictrltreeview_selectitembyindex _guictrltreeview_setbkcolor "
    "_guictrltreeview_setbold _guictrltreeview_setchecked _guictrltreeview_setcheckedbyindex "
    "_guictrltreeview_setchildren _guictrltreeview_setcut _guictrltreeview_setdroptarget _guictrltreeview_setfocused "
    "_guictrltreeview_setheight _guictrltreeview_seticon _guictrltreeview_setimageindex _guictrltreeview_setindent "
    "_guictrltreeview_setinsertmark _guictrltreeview_setinsertmarkcolor _guictrltreeview_setitemheight "
    "_guictrltreeview_setitemparam _guictrltreeview_setlinecolor _guictrltreeview_setnormalimagelist "
    "_guictrltreeview_setscrolltime _guictrltreeview_setselected _guictrltreeview_setselectedimageindex "
    "_guictrltreeview_setstate _guictrltreeview_setstateimageindex _guictrltreeview_setstateimagelist "
    "_guictrltreeview_settext _guictrltreeview_settextcolor _guictrltreeview_settooltips "
    "_guictrltreeview_setunicodeformat _guictrltreeview_sort "
    "_guiimagelist_add _guiimagelist_addbitmap _guiimagelist_addicon _guiimagelist_addmasked _guiimagelist_begindrag "
    "_guiimagelist_copy _guiimagelist_create _guiimagelist_destroy _guiimagelist_destroyicon "
    "_guiimagelist_dragenter _guiimagelist_dragleave _guiimagelist_dragmove _guiimagelist_draw _guiimagelist_drawex "
    "_guiimagelist_duplicate _guiimagelist_enddrag _guiimagelist_getbkcolor _guiimagelist_geticon "
    "_guiimagelist_geticonheight _guiimagelist_geticonsize _guiimagelist_geticonsizeex _guiimagelist_geticonwidth "
    "_guiimagelist_getimagecount _guiimagelist_getimageinfoex _guiimagelist_remove _guiimagelist_replaceicon "
    "_guiimagelist_setbkcolor _guiimagelist_seticonsize _guiimagelist_setimagecount _guiimagelist_swap "
    "_guiscrollbars_enablescrollbar _guiscrollbars_getscrollbarinfoex "
    "_guiscrollbars_getscrollbarrect _guiscrollbars_getscrollbarrgstate _guiscrollbars_getscrollbarxylinebutton "
    "_guiscrollbars_getscrollbarxythumbbottom _guiscrollbars_getscrollbarxythumbtop _guiscrollbars_getscrollinfo "
    "_guiscrollbars_getscrollinfoex _guiscrollbars_getscrollinfomax _guiscrollbars_getscrollinfomin "
    "_guiscrollbars_getscrollinfopage _guiscrollbars_getscrollinfopos _guiscrollbars_getscrollinfotrackpos "
    "_guiscrollbars_getscrollpos _guiscrollbars_getscrollrange _guiscrollbars_init _guiscrollbars_scrollwindow "
    "_guiscrollbars_setscrollinfo _guiscrollbars_setscrollinfomax _guiscrollbars_setscrollinfomin "
    "_guiscrollbars_setscrollinfopage _guiscrollbars_setscrollinfopos _guiscrollbars_setscrollrange "
    "_guiscrollbars_showscrollbar _guitooltip_activate _guitooltip_addtool _guitooltip_adjustrect _guitooltip_bitstottf "
    "_guitooltip_create _guitooltip_deactivate _guitooltip_deltool _guitooltip_destroy _guitooltip_enumtools "
    "_guitooltip_getbubbleheight _guitooltip_getbubblesize _guitooltip_getbubblewidth _guitooltip_getcurrenttool "
    "_guitooltip_getdelaytime _guitooltip_getmargin _guitooltip_getmarginex _guitooltip_getmaxtipwidth _guitooltip_gettext "
    "_guitooltip_gettipbkcolor _guitooltip_gettiptextcolor _guitooltip_gettitlebitmap _guitooltip_gettitletext "
    "_guitooltip_gettoolcount _guitooltip_gettoolinfo _guitooltip_hittest _guitooltip_newtoolrect "
    "_guitooltip_pop _guitooltip_popup _guitooltip_setdelaytime _guitooltip_setmargin _guitooltip_setmaxtipwidth "
    "_guitooltip_settipbkcolor _guitooltip_settiptextcolor _guitooltip_settitle _guitooltip_settoolinfo "
    "_guitooltip_setwindowtheme _guitooltip_toolexists _guitooltip_tooltoarray _guitooltip_trackactivate "
    "_guitooltip_trackposition _guitooltip_update _guitooltip_updatetiptext _hextostring _ie_example "
    "_ie_introduction _ie_versioninfo _ieaction _ieattach _iebodyreadhtml _iebodyreadtext _iebodywritehtml "
    "_iecreate _iecreateembedded _iedocgetobj _iedocinserthtml _iedocinserttext _iedocreadhtml _iedocwritehtml "
    "_ieerrornotify _ieformelementcheckboxselect _ieformelementgetcollection _ieformelementgetobjbyname "
    "_ieformelementgetvalue _ieformelementoptionselect _ieformelementradioselect _ieformelementsetvalue "
    "_ieformgetcollection _ieformgetobjbyname _ieformimageclick _ieformreset _ieformsubmit "
    "_ieframegetcollection _ieframegetobjbyname _iegetobjbyid _iegetobjbyname _ieheadinserteventscript "
    "_ieimgclick _ieimggetcollection _ieisframeset _ielinkclickbyindex _ielinkclickbytext _ielinkgetcollection "
    "_ieloadwait _ieloadwaittimeout _ienavigate _iepropertyget _iepropertyset _iequit _ietablegetcollection "
    "_ietablewritetoarray _ietagnameallgetcollection _ietagnamegetcollection _inetexplorercapable _inetgetsource "
    "_inetmail _inetsmtpmail _ispressed _max _memglobalalloc _memglobalfree _memgloballock _memglobalrealloc "
    "_memglobalsize _memglobalunlock _memmovememory _memvirtualalloc _memvirtualallocex _memvirtualfree "
    "_memvirtualfreeex _min _mousetrap _namedpipes_callnamedpipe _namedpipes_connectnamedpipe "
    "_namedpipes_createnamedpipe _namedpipes_createpipe _namedpipes_disconnectnamedpipe "
    "_namedpipes_getnamedpipehandlestate _namedpipes_getnamedpipeinfo _namedpipes_peeknamedpipe "
    "_namedpipes_setnamedpipehandlestate _namedpipes_transactnamedpipe _namedpipes_waitnamedpipe "
    "_net_share_connectionenum _net_share_fileclose _net_share_fileenum _net_share_filegetinfo _net_share_permstr "
    "_net_share_resourcestr _net_share_sessiondel _net_share_sessionenum _net_share_sessiongetinfo "
    "_net_share_shareadd _net_share_sharecheck _net_share_sharedel _net_share_shareenum _net_share_sharegetinfo "
    "_net_share_sharesetinfo _net_share_statisticsgetsvr _net_share_statisticsgetwrk _now _nowcalc _nowcalcdate "
    "_nowdate _nowtime _pathfull _pathgetrelative _pathmake _pathsplit _processgetname _processgetpriority "
    "_radian _replacestringinfile _rundos _screencapture_capture _screencapture_capturewnd _screencapture_saveimage "
    "_screencapture_setbmpformat _screencapture_setjpgquality _screencapture_settifcolordepth "
    "_screencapture_settifcompression _security__adjusttokenprivileges _security__createprocesswithtoken "
    "_security__duplicatetokenex _security__getaccountsid _security__getlengthsid _security__gettokeninformation "
    "_security__impersonateself _security__isvalidsid _security__lookupaccountname _security__lookupaccountsid "
    "_security__lookupprivilegevalue _security__openprocesstoken _security__openthreadtoken "
    "_security__openthreadtokenex _security__setprivilege _security__settokeninformation _security__sidtostringsid "
    "_security__sidtypestr _security__stringsidtosid _sendmessage _sendmessagea _setdate _settime _singleton "
    "_soundclose _soundlength _soundopen _soundpause _soundplay _soundpos _soundresume _soundseek _soundstatus "
    "_soundstop _sqlite_changes _sqlite_close _sqlite_display2dresult _sqlite_encode _sqlite_errcode _sqlite_errmsg "
    "_sqlite_escape _sqlite_exec _sqlite_fastencode _sqlite_fastescape _sqlite_fetchdata _sqlite_fetchnames "
    "_sqlite_gettable _sqlite_gettable2d _sqlite_gettabledata2d _sqlite_lastinsertrowid _sqlite_libversion "
    "_sqlite_open _sqlite_query _sqlite_queryfinalize _sqlite_queryreset _sqlite_querysinglerow "
    "_sqlite_safemode _sqlite_settimeout _sqlite_shutdown _sqlite_sqliteexe _sqlite_startup _sqlite_totalchanges "
    "_stringbetween _stringexplode _stringinsert _stringproper _stringrepeat _stringtitlecase _stringtohex "
    "_tcpiptoname _tempfile _tickstotime _timer_diff _timer_getidletime _timer_gettimerid _timer_init "
    "_timer_killalltimers _timer_killtimer _timer_settimer _timetoticks _versioncompare _viclose _viexeccommand "
    "_vifindgpib _vigpibbusreset _vigtl _viinteractivecontrol _viopen _visetattribute _visettimeout _weeknumberiso "
    "_winapi_attachconsole _winapi_attachthreadinput _winapi_beep _winapi_bitblt _winapi_callnexthookex "
    "_winapi_callwindowproc _winapi_clienttoscreen _winapi_closehandle _winapi_combinergn "
    "_winapi_commdlgextendederror _winapi_copyicon _winapi_createbitmap _winapi_createcompatiblebitmap "
    "_winapi_createcompatibledc _winapi_createevent _winapi_createfile _winapi_createfont "
    "_winapi_createfontindirect _winapi_createpen _winapi_createprocess _winapi_createrectrgn "
    "_winapi_createroundrectrgn _winapi_createsolidbitmap _winapi_createsolidbrush _winapi_createwindowex "
    "_winapi_defwindowproc _winapi_deletedc _winapi_deleteobject _winapi_destroyicon _winapi_destroywindow "
    "_winapi_drawedge _winapi_drawframecontrol _winapi_drawicon _winapi_drawiconex _winapi_drawline "
    "_winapi_drawtext _winapi_duplicatehandle _winapi_enablewindow _winapi_enumdisplaydevices _winapi_enumwindows "
    "_winapi_enumwindowspopup _winapi_enumwindowstop _winapi_expandenvironmentstrings _winapi_extracticonex "
    "_winapi_fatalappexit _winapi_fillrect _winapi_findexecutable _winapi_findwindow _winapi_flashwindow "
    "_winapi_flashwindowex _winapi_floattoint _winapi_flushfilebuffers _winapi_formatmessage _winapi_framerect "
    "_winapi_freelibrary _winapi_getancestor _winapi_getasynckeystate _winapi_getbkmode _winapi_getclassname "
    "_winapi_getclientheight _winapi_getclientrect _winapi_getclientwidth _winapi_getcurrentprocess "
    "_winapi_getcurrentprocessid _winapi_getcurrentthread _winapi_getcurrentthreadid _winapi_getcursorinfo "
    "_winapi_getdc _winapi_getdesktopwindow _winapi_getdevicecaps _winapi_getdibits _winapi_getdlgctrlid "
    "_winapi_getdlgitem _winapi_getfilesizeex _winapi_getfocus _winapi_getforegroundwindow "
    "_winapi_getguiresources _winapi_geticoninfo _winapi_getlasterror _winapi_getlasterrormessage "
    "_winapi_getlayeredwindowattributes _winapi_getmodulehandle _winapi_getmousepos _winapi_getmouseposx "
    "_winapi_getmouseposy _winapi_getobject _winapi_getopenfilename _winapi_getoverlappedresult _winapi_getparent "
    "_winapi_getprocessaffinitymask _winapi_getsavefilename _winapi_getstdhandle _winapi_getstockobject "
    "_winapi_getsyscolor _winapi_getsyscolorbrush _winapi_getsystemmetrics _winapi_gettextextentpoint32 "
    "_winapi_gettextmetrics _winapi_getwindow _winapi_getwindowdc _winapi_getwindowheight _winapi_getwindowlong "
    "_winapi_getwindowplacement _winapi_getwindowrect _winapi_getwindowrgn _winapi_getwindowtext "
    "_winapi_getwindowthreadprocessid _winapi_getwindowwidth _winapi_getxyfrompoint _winapi_globalmemorystatus "
    "_winapi_guidfromstring _winapi_guidfromstringex _winapi_hiword _winapi_inprocess _winapi_inttofloat "
    "_winapi_invalidaterect _winapi_isclassname _winapi_iswindow _winapi_iswindowvisible _winapi_lineto "
    "_winapi_loadbitmap _winapi_loadimage _winapi_loadlibrary _winapi_loadlibraryex _winapi_loadshell32icon "
    "_winapi_loadstring _winapi_localfree _winapi_loword _winapi_makelangid _winapi_makelcid _winapi_makelong "
    "_winapi_makeqword _winapi_messagebeep _winapi_mouse_event _winapi_moveto _winapi_movewindow _winapi_msgbox "
    "_winapi_muldiv _winapi_multibytetowidechar _winapi_multibytetowidecharex _winapi_openprocess "
    "_winapi_pathfindonpath _winapi_pointfromrect _winapi_postmessage _winapi_primarylangid _winapi_ptinrect "
    "_winapi_readfile _winapi_readprocessmemory _winapi_rectisempty _winapi_redrawwindow "
    "_winapi_registerwindowmessage _winapi_releasecapture _winapi_releasedc _winapi_screentoclient "
    "_winapi_selectobject _winapi_setbkcolor _winapi_setbkmode _winapi_setcapture _winapi_setcursor "
    "_winapi_setdefaultprinter _winapi_setdibits _winapi_setendoffile _winapi_setevent _winapi_setfilepointer "
    "_winapi_setfocus _winapi_setfont _winapi_sethandleinformation _winapi_setlasterror "
    "_winapi_setlayeredwindowattributes _winapi_setparent _winapi_setprocessaffinitymask _winapi_setsyscolors "
    "_winapi_settextcolor _winapi_setwindowlong _winapi_setwindowplacement _winapi_setwindowpos "
    "_winapi_setwindowrgn _winapi_setwindowshookex _winapi_setwindowtext _winapi_showcaret _winapi_showcursor "
    "_winapi_showerror _winapi_showlasterror _winapi_showmsg _winapi_showownedpopups _winapi_showwindow "
    "_winapi_stringfromguid _winapi_stringlena _winapi_stringlenw _winapi_sublangid _winapi_systemparametersinfo "
    "_winapi_twipsperpixelx _winapi_twipsperpixely _winapi_unhookwindowshookex _winapi_updatelayeredwindow "
    "_winapi_updatewindow _winapi_waitforinputidle _winapi_waitformultipleobjects _winapi_waitforsingleobject "
    "_winapi_widechartomultibyte _winapi_windowfrompoint _winapi_writeconsole _winapi_writefile _winapi_writeprocessmemory "
    "_winnet_addconnection _winnet_addconnection2 _winnet_addconnection3 _winnet_cancelconnection "
    "_winnet_cancelconnection2 _winnet_closeenum _winnet_connectiondialog _winnet_connectiondialog1 "
    "_winnet_disconnectdialog _winnet_disconnectdialog1 _winnet_enumresource _winnet_getconnection "
    "_winnet_getconnectionperformance _winnet_getlasterror _winnet_getnetworkinformation _winnet_getprovidername "
    "_winnet_getresourceinformation _winnet_getresourceparent _winnet_getuniversalname _winnet_getuser "
    "_winnet_openenum _winnet_restoreconnection _winnet_useconnection _word_create _word_docadd _word_docattach "
    "_word_docclose _word_docexport _word_docfind _word_docfindreplace _word_docget _word_doclinkadd "
    "_word_doclinkget _word_docopen _word_docpictureadd _word_docprint _word_docrangeset _word_docsave "
    "_word_docsaveas _word_doctableread _word_doctablewrite _word_quit",
    NULL,
};


EDITLEXER lexAU3 =
{
    SCLEX_AU3, "au3", IDS_LEX_AUTOIT3, L"AutoIt3 Script", L"au3", L"",
    &KeyWords_AU3, {
        { {STYLE_DEFAULT}, IDS_LEX_STR_Default, L"Default", L"", L"" },
        //{ SCE_AU3_DEFAULT, IDS_LEX_STR_Default, L"Default", L"", L"" },
        { {MULTI_STYLE(SCE_AU3_COMMENT,SCE_AU3_COMMENTBLOCK,0,0)}, IDS_LEX_STR_Comment, L"Comment", L"fore:#008000", L"" },
        { {SCE_AU3_NUMBER}, IDS_LEX_STR_Number, L"Number", L"fore:#008080", L"" },
        { {SCE_AU3_FUNCTION}, IDS_LEX_STR_63277, L"Function", L"fore:#0000FF", L"" },
        { {SCE_AU3_UDF}, IDS_LEX_STR_63305, L"User-Defined Function", L"fore:#0000FF", L"" },
        { {SCE_AU3_KEYWORD}, IDS_LEX_STR_Keyword, L"Keyword", L"fore:#0000FF", L"" },
        { {SCE_AU3_MACRO}, IDS_LEX_STR_PageEx, L"Macro", L"fore:#0080FF", L"" },
        { {SCE_AU3_STRING}, IDS_LEX_STR_String, L"String", L"fore:#008080", L"" },
        { {SCE_AU3_OPERATOR}, IDS_LEX_STR_Operator, L"Operator", L"fore:#C000C0", L"" },
        { {SCE_AU3_VARIABLE}, IDS_LEX_STR_Var, L"Variable", L"fore:#808000", L"" },
        { {SCE_AU3_SENT}, IDS_LEX_STR_SendKey, L"Send Key", L"fore:#FF0000", L"" },
        { {SCE_AU3_PREPROCESSOR}, IDS_LEX_STR_PreProc, L"Preprocessor", L"fore:#FF8000", L"" },
        { {SCE_AU3_SPECIAL}, IDS_LEX_STR_Special, L"Special", L"fore:#FF8000", L"" },
        EDITLEXER_SENTINEL
    }
};
