//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Notepad3\grepWinNP3\src\Resources\grepWin.rc
// encoding: CP-1252
#define IDS_APP_TITLE                   103
#define IDS_NAME                        104
#define IDS_SEARCHSTRING                105
#define IDS_REPLACESTRING               106
#define IDI_GREPWIN                     107
#define IDS_NOTESTTEXTAVAILABLE         107
#define IDS_SEARCHSTRINGEMPTY           108
#define IDC_GREPWIN                     109
#define IDS_NOREPLACETEXT               110
#define IDS_NOMATCH                     111
#define IDS_PATTERN_TT                  112
#define IDS_EXCLUDEDIR_TT               113
#define IDS_SEARCHPATH_TT               114
#define IDS_DOTMATCHNEWLINE_TT          115
#define IDS_SEARCHTEXT_TT               116
#define IDS_ONLYONE_TT                  117
#define IDS_EDITMULTILINE_TT            118
#define IDS_ABOUT                       119
#define IDS_LESSTHAN                    120
#define IDS_EQUALTO                     121
#define IDS_GREATERTHAN                 122
#define IDS_SEARCH                      123
#define IDS_REPLACECONFIRM              124
#define IDS_ANEMPTYSTRING               125
#define IDS_STOP                        126
#define IDS_SELECTPATHTOSEARCH          127
#define IDS_INFOLABEL                   128
#define IDD_SEARCHDLG                   129
#define IDS_READERROR                   129
#define IDD_REGEXTEST                   130
#define IDS_BINARY                      130
#define IDD_NAME                        131
#define IDS_REGEXOK                     131
#define IDD_BOOKMARKS                   132
#define IDS_REGEXINVALID                132
#define IDC_BKPOPUP                     133
#define IDS_SIZE                        133
#define IDR_INFODLG                     134
#define IDS_LINE                        134
#define IDD_ABOUT                       135
#define IDS_MATCHES                     135
#define IDR_SEARCHDLG                   136
#define IDS_TEXT                        136
#define IDD_MULTILINEEDIT               137
#define IDS_PATH                        137
#define IDD_SETTINGS                    138
#define IDS_ENCODING                    138
#define IDS_DATEMODIFIED                139
#define IDS_SELECTEDITOR                140
#define IDS_OPENWITHEDITOR              141
#define IDS_OPENCONTAININGFOLDER        142
#define IDS_COPYPATH                    143
#define IDS_COPYPATHS                   144
#define IDS_COPYFILENAME                145
#define IDS_COPYFILENAMES               146
#define IDS_COPYRESULT                  147
#define IDS_COPYRESULTS                 148
#define IDS_XMOREMATCHES                149
#define IDS_CONTEXTLINE                 150
#define IDS_INFOLABELFILE               151
#define IDS_ERR_RELATIVEPATH            152
#define IDS_ERR_INVALID_PATH            153
#define IDS_PROGRAMS                    154
#define IDS_ALLFILES                    155
#define IDS_BACKUPINFOLDER_TT           156
#define IDS_SHIFT_NOTSEARCH             157
#define IDS_FILEEXT                     158
#define IDS_DARKMODE_TT                 159
#define IDS_ERR_PATHNOTEXIST            160
#define IDS_INVERSESEARCH               161
#define IDS_SEARCHINFOUNDFILES          162
#define IDS_EXPORT_TT                   163
#define IDS_EXPORTTITLE                 164
#define IDS_EXPORTPATHS                 165
#define IDS_EXPORTMATCHLINENUMBER       166
#define IDS_EXPORTMATCHLINECONTENT      167
#define IDS_UPDATEAVAILABLE             168
#define IDS_CAPTURESEARCH               169
#define IDC_SEARCHTEXT                  1000
#define IDC_REGEXRADIO                  1001
#define IDC_TEXTRADIO                   1002
#define IDC_REGEXOKLABEL                1004
#define IDC_ALLSIZERADIO                1005
#define IDC_SIZERADIO                   1006
#define IDC_SIZECOMBO                   1007
#define IDC_SIZEEDIT                    1008
#define IDC_INCLUDESYSTEM               1009
#define IDC_INCLUDEHIDDEN               1010
#define IDC_INCLUDESUBFOLDERS           1011
#define IDC_SEARCHPATH                  1012
#define IDC_SEARCHPATHBROWSE            1013
#define IDC_RESULTLIST                  1014
#define IDC_GROUPSEARCHIN               1015
#define IDC_GROUPSEARCHFOR              1016
#define IDC_GROUPLIMITSEARCH            1017
#define IDC_GROUPSEARCHRESULTS          1018
#define IDC_KBTEXT                      1019
#define IDC_SEARCHINFOLABEL             1020
#define IDC_ADDTOBOOKMARKS              1021
#define IDC_BOOKMARKS                   1022
#define IDC_REPLACETEXT                 1023
#define IDC_SEARCHFORLABEL              1026
#define IDC_REPLACEWITHLABEL            1027
#define IDC_TESTREGEX                   1028
#define IDC_CREATEBACKUP                1029
#define IDC_TEXTCONTENT                 1030
#define IDC_REGEXMATCH                  1031
#define IDC_REGEXREPLACED               1032
#define IDC_NAME                        1037
#define IDC_PATTERNLABEL                1039
#define IDC_PATTERN                     1040
#define IDC_EXCLUDE_DIRS_PATTERNLABEL   1041
#define IDC_CASE_SENSITIVE              1042
#define IDC_VERSIONINFO                 1043
#define IDC_EXCLUDEDIRSPATTERN          1043
#define IDC_DATE                        1044
#define IDC_WEBLINK                     1045
#define IDC_FILEPATTERNREGEX            1046
#define IDC_FILEPATTERNTEXT             1048
#define IDC_REPLACE                     1049
#define IDC_INCLUDEBINARY               1050
#define IDC_DOTMATCHNEWLINE             1051
#define IDC_ABOUTLINK                   1052
#define IDC_UTF8                        1053
#define IDC_UTF9                        1054
#define IDC_BINARY                      1054
#define IDC_INFOLABEL                   1056
#define IDC_RESULTFILES                 1059
#define IDC_RADIO2                      1060
#define IDC_RESULTCONTENT               1060
#define IDC_BUTTON1                     1061
#define IDC_HELPBUTTON                  1061
#define IDC_EDITMULTILINE1              1061
#define IDC_CHECK1                      1062
#define IDC_ESCKEY                      1062
#define IDC_INCLUDEPATH                 1062
#define IDC_EDITMULTILINE2              1063
#define IDC_ONLYONE                     1063
#define IDC_PATHMRU                     1064
#define IDC_DARKMODE                    1064
#define IDC_HELPLABEL                   1065
#define IDC_EXCLUDEDIRMRU               1066
#define IDC_EDITORCMD                   1066
#define IDC_PATTERNMRU                  1067
#define IDC_EDITORGROUP                 1067
#define IDC_STATIC1                     1068
#define IDC_STATIC2                     1069
#define IDC_SETTINGSBUTTON              1071
#define IDC_PROGRESS                    1072
#define IDC_LANGUAGE                    1073
#define IDC_STATIC3                     1074
#define IDC_STATIC4                     1075
#define IDC_DWM                         1076
#define IDC_BACKUPINFOLDER              1077
#define IDC_RADIO_DATE_ALL              1078
#define IDC_BACKUPINFOLDER2             1078
#define IDC_NOWARNINGIFNOBACKUP         1078
#define IDC_RADIO_DATE_NEWER            1079
#define IDC_RADIO_DATE_OLDER            1080
#define IDC_RADIO_DATE_BETWEEN          1081
#define IDC_DATEPICK1                   1082
#define IDC_DATEPICK2                   1083
#define IDC_DARKMODEINFO                1083
#define IDC_INVERSESEARCH               1084
#define IDC_SEARCHINFOUNDFILES          1085
#define IDC_EXPORT                      1086
#define IDC_UPDATELINK                  1087
#define IDC_DOUPDATECHECKS              1088
#define IDC_CAPTURESEARCH               1089
#define IDC_NUMNULL                     1090

#define IDC_RESETDEFAULT                3000
#define IDC_NP3_DISCLAIMER              3001
#define IDC_SPIN_MAXWORKER              3002
#define IDC_MAXNUMWORKER                3003
#define IDC_TEXT_NUMOFWORKER            3004
#define IDC_ENTRYCONTEXTMENU            3005


#define ID_REMOVEBOOKMARK               32771
#define ID_DUMMY_RENAMEPRESET           32774
#define ID_RENAMEBOOKMARK               32775
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
