//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Notepad3.rc
//
#define IDR_RT_MANIFEST                   1
#define IDR_MAINWND                       100
#define IDC_FINDTEXT                      101
#define IDC_LINENUM                       102
#define IDC_COMMANDLINE                   103
#define IDD_ABOUT                         104
#define IDC_VERSION                       105
#define IDC_OPENWITHDIR                   106
#define IDC_FILEMRU                       107
#define IDC_STYLELIST                     108
#define IDC_FAVORITESDIR                  109
#define IDC_COLUMNWRAP                    110
#define IDC_INFOBOXICON                   111
#define IDC_COPY                          112
#define IDC_ENCODINGLIST                  113
#define IDC_SEARCHEXE                     114
#define IDR_POPUPMENU                     115
#define IDC_GETOPENWITHDIR                116
#define IDC_RESIZEGRIP                    117
#define IDD_OPENWITH                      118
#define IDC_REPLACETEXT                   119
#define IDI_RUN                           120
#define IDC_COLNUM                        121
#define IDC_DEFAULTSCHEME                 122
#define IDC_GETFAVORITESDIR               123
#define IDC_INFOBOXTEXT                   124
#define IDB_OPEN                          125
#define IDR_ACCFINDREPLACE                126
#define IDC_STYLELABEL_ROOT               127
#define IDC_STYLELABEL                    128
#define IDC_STYLEEDIT_ROOT                129
#define IDC_STYLEEDIT                     130
#define IDC_STYLEBACK                     131
#define IDC_STYLEFONT                     132
#define IDC_STYLEDEFAULT                  133
#define IDC_PREVIEW                       134
#define IDC_PREVSTYLE                     135
#define IDC_NEXTSTYLE                     136
#define IDC_IMPORT                        137
#define IDC_EXPORT                        138
#define IDC_RESIZEGRIP4                   139
#define IDC_NOUNICODEDETECTION            140
#define IDC_COPYRIGHT                     141
#define IDC_FINDCASE                      142
#define IDC_OPENWITHDESCR                 143
#define IDC_SAVEMRU                       144
#define IDD_RUN                           145
#define IDC_AUTOSELECT                    146
#define IDC_FAVORITESDESCR                147
#define IDC_INFOBOXCHECK                  148
#define IDC_CONSISTENTEOLS                149
#define IDB_PREV                          150
#define IDI_STYLES                        151
#define IDC_ASCIIASUTF8                   152
#define IDC_WEBPAGE                       153
#define IDD_DEFENCODING                   154
#define IDC_FINDWORD                      155
#define IDC_RESIZEGRIP3                   156
#define IDB_NEXT                          157
#define IDC_STYLEFORE                     158
#define IDC_AUTOSTRIPBLANKS               159
#define IDC_ENCODINGFROMFILEVARS          160
#define IDC_WEBPAGE2                      161
#define IDC_PRESERVECARET                 162
#define IDC_MODWEBPAGE2                   163
#define IDD_ENCODING                      164
#define IDC_MOD_PAGE2                     165
#define IDC_FINDSTART                     166
#define IDB_PICK                          167
#define IDC_AUTHORNAME                    168
#define IDC_WEBPAGE4                      169
#define IDC_MODWEBPAGE                    170
#define IDD_RECODE                        171
#define IDC_FINDREGEXP                    172
#define IDB_ENCODING                      173
#define IDC_EMAIL                         174
#define IDC_NOTE2WEBPAGE                  175
#define IDD_DEFEOLMODE                    176
#define IDC_FINDTRANSFORMBS               177
#define IDC_EMAIL2                        178
#define IDC_NOTE2WEBPAGE2                 179
#define IDD_FAVORITES                     180
#define IDC_NOWRAP                        181
#define IDD_ADDTOFAV                      182
#define IDC_FINDCLOSE                     183
#define IDC_EMAIL3                        184
#define IDD_FILEMRU                       186
#define IDC_FINDPREV                      187
#define IDD_CHANGENOTIFY                  188
#define IDD_MODIFYLINES                   189
#define IDC_MOD_PAGE                      190
#define IDC_REPLACE                       191
#define IDC_TITLE                         192
#define IDD_ALIGN                         193
#define IDC_WEBPAGE3                      194
#define IDD_ENCLOSESELECTION              195
#define IDC_REPLACEALL                    196
#define IDD_INSERTTAG                     198
#define IDC_REPLACEINSEL                  199
#define IDD_SORT                          200
#define IDC_TOGGLEFINDREPLACE             201
#define IDD_COLUMNWRAP                    202
#define IDD_LINENUM                       203
#define IDD_FIND                          204
#define IDD_REPLACE                       205
#define IDD_STYLESELECT                   206
#define IDD_STYLECONFIG                   207
#define IDD_WORDWRAP                      208
#define IDD_LONGLINES                     209
#define IDD_TABSETTINGS                   210
#define IDD_PAGESETUP                     211
#define IDD_INFOBOX                       212
#define IDD_INFOBOX2                      213
#define IDD_INFOBOX3                      214
#define IDT_TIMER_MRKALL                  215
#define IDC_ALL_OCCURRENCES               216
#define IDC_MARKALL_OCC                   217
#define IDC_DOT_MATCH_ALL                 218
#define IDT_TIMER_MAIN_MRKALL             219
#define IDC_MAIN_MARKALL_OCC              220
#define IDT_TIMER_UPDATE_HOTSPOT          221
#define IDC_CALL_UPDATE_HOTSPOT           222
#define IDC_BACKSLASHHELP                 223
#define IDC_REGEXPHELP                    224
#define IDC_WILDCARDHELP                  225
#define IDC_WILDCARDSEARCH                226
#define IDC_SCI_VERSION                   227
#define IDR_MAINWNDTB                     228
#define IDC_REMOVE                        229
#define IDC_SWAPSTRG                      230
#define IDC_CHECK_OCC                     231
#define IDC_PRINTER                       232
#define IDC_USEASREADINGFALLBACK          233
#define IDR_ACCCUSTOMSCHEMES              234
#define IDC_NOANSICPDETECTION             235
#define IDC_REMEMBERSEARCHPATTERN         236
#define IDACC_FIND                        302
#define IDACC_REPLACE                     303
#define IDACC_SAVEPOS                     304
#define IDACC_RESETPOS                    305
#define IDACC_FINDNEXT                    306
#define IDACC_FINDPREV                    307
#define IDACC_REPLACENEXT                 308
#define IDACC_SAVEFIND                    309
#define IDACC_SELTONEXT                   310
#define IDACC_SELTOPREV                   311
#define IDACC_VIEWSCHEMECONFIG            312
#define IDACC_PREVIEW                     313
#define IDC_NFOASOEM                      400
#define IDC_COMPILER                      401
#define IDC_SETCURLEXERTV                 402
#define IDD_READPW                        501
#define IDC_CHECK1                        502
#define IDC_EDIT1                         503
#define IDC_EDIT2                         504
#define IDC_CHECK2                        505
#define IDC_STATICPW                      506
#define IDC_CHECK3                        507
#define IDM_SETPASS                       508
#define IDD_PASSWORDS                     509
#define IDC_EDIT3                         510
#define IDS_PASS_FAILURE                  511
#define IDS_NOPASS                        512
#define IDM_HELP_UPDATEINSTALLER          513
#define IDM_HELP_UPDATEWEBSITE            514
#define IDS_FR_STATUS_TEXT                515
#define IDR_MAINWNDTB2                    550
#define IDR_MAINWND128                    551
#define IDC_RICHEDITABOUT                 552
#define IDC_COPYVERSTRG                   553
#define IDR_RIZBITMAP                     554
#define IDC_RIZONEBMP                     555
#define IDS_APPTITLE                      10000
#define IDS_APPTITLE_ELEVATED             10001
#define IDS_APPTITLE_PASTEBOARD           10002
#define IDS_UNTITLED                      10003
#define IDS_TITLEEXCERPT                  10004
#define IDS_READONLY                      10005
#define IDS_DOCPOS                        10006
#define IDS_DOCPOS2                       10007
#define IDS_DOCSIZE                       10008
#define IDS_LOADFILE                      10009
#define IDS_SAVEFILE                      10010
#define IDS_PRINTFILE                     10011
#define IDS_SAVINGSETTINGS                10012
#define IDS_LINKDESCRIPTION               10013
#define IDS_FILTER_ALL                    10014
#define IDS_FILTER_EXE                    10015
#define IDS_FILTER_INI                    10016
#define IDS_OPENWITH                      10017
#define IDS_FAVORITES                     10018
#define IDS_BACKSLASHHELP                 10019
#define IDS_REGEXPHELP                    10020
#define IDS_WILDCARDHELP                  10021
#define IDS_FR_STATUS_FMT                 10022
#define CMD_ESCAPE                        20000
#define CMD_SHIFTESC                      20001
#define CMD_SHIFTCTRLENTER                20002
#define CMD_CTRLLEFT                      20003
#define CMD_CTRLRIGHT                     20004
#define CMD_DELETEBACK                    20005
#define CMD_CTRLBACK                      20006
#define CMD_DEL                           20007
#define CMD_CTRLDEL                       20008
#define CMD_CTRLTAB                       20009
#define CMD_RECODEDEFAULT                 20010
#define CMD_RECODEANSI                    20011
#define CMD_RECODEOEM                     20012
#define CMD_RELOADASCIIASUTF8             20013
#define CMD_RELOADNOFILEVARS              20014
#define CMD_LEXDEFAULT                    20015
#define CMD_LEXHTML                       20016
#define CMD_LEXXML                        20017
#define CMD_TIMESTAMPS                    20018
#define CMD_WEBACTION1                    20019
#define CMD_WEBACTION2                    20020
#define CMD_FINDNEXTSEL                   20021
#define CMD_FINDPREVSEL                   20022
#define CMD_INCLINELIMIT                  20023
#define CMD_DECLINELIMIT                  20024
#define CMD_STRINGIFY                     20025
#define CMD_STRINGIFY2                    20026
#define CMD_EMBRACE                       20027
#define CMD_EMBRACE2                      20028
#define CMD_EMBRACE3                      20029
#define CMD_EMBRACE4                      20030
#define CMD_INCREASENUM                   20031
#define CMD_DECREASENUM                   20032
#define CMD_TOGGLETITLE                   20033
#define CMD_JUMP2SELSTART                 20034
#define CMD_JUMP2SELEND                   20035
#define CMD_COPYPATHNAME                  20036
#define CMD_COPYWINPOS                    20037
#define CMD_DEFAULTWINPOS                 20038
#define CMD_OPENINIFILE                   20039
#define CMD_CTRLENTER                     20040
#define CMD_OPEN_HYPERLINK                20041
#define CMD_ALTUP                         20042
#define CMD_ALTDOWN                       20043
#define CMD_ALTLEFT                       20044
#define CMD_ALTRIGHT                      20045
#define CMD_TAB                           20046
#define CMD_BACKTAB                       20047
#define IDM_FILE_NEW                      40000
#define IDM_FILE_OPEN                     40001
#define IDM_FILE_REVERT                   40002
#define IDM_FILE_BROWSE                   40003
#define IDM_FILE_SAVE                     40004
#define IDM_FILE_SAVEAS                   40005
#define IDM_FILE_SAVECOPY                 40006
#define IDM_FILE_READONLY                 40007
#define IDM_FILE_LAUNCH                   40008
#define IDM_FILE_OPENWITH                 40009
#define IDM_FILE_RUN                      40010
#define IDM_FILE_NEWWINDOW                40011
#define IDM_FILE_NEWWINDOW2               40012
#define IDM_FILE_PAGESETUP                40013
#define IDM_FILE_PRINT                    40014
#define IDM_FILE_PROPERTIES               40015
#define IDM_FILE_CREATELINK               40016
#define IDM_FILE_OPENFAV                  40017
#define IDM_FILE_ADDTOFAV                 40018
#define IDM_FILE_MANAGEFAV                40019
#define IDM_FILE_RECENT                   40020
#define IDM_FILE_EXIT                     40021
#define IDM_ENCODING_ANSI                 40100
#define IDM_ENCODING_UNICODE              40101
#define IDM_ENCODING_UNICODEREV           40102
#define IDM_ENCODING_UTF8                 40103
#define IDM_ENCODING_UTF8SIGN             40104
#define IDM_ENCODING_SELECT               40105
#define IDM_ENCODING_RECODE               40106
#define IDM_ENCODING_SETDEFAULT           40107
#define IDM_LINEENDINGS_CRLF              40200
#define IDM_LINEENDINGS_LF                40201
#define IDM_LINEENDINGS_CR                40202
#define IDM_LINEENDINGS_SETDEFAULT        40203
#define IDM_EDIT_BOOKMARKTOGGLE           40250
#define IDM_EDIT_BOOKMARKNEXT             40251
#define IDM_EDIT_BOOKMARKCLEAR            40252
#define IDM_EDIT_BOOKMARKPREV             40253
#define BME_EDIT_BOOKMARKTOGGLE           40254
#define BME_EDIT_BOOKMARKNEXT             40255
#define BME_EDIT_BOOKMARKCLEAR            40256
#define BME_EDIT_BOOKMARKPREV             40257
#define IDM_EDIT_UNDO                     40300
#define IDM_EDIT_REDO                     40301
#define IDM_EDIT_CUT                      40302
#define IDM_EDIT_COPY                     40303
#define IDM_EDIT_COPYALL                  40304
#define IDM_EDIT_COPYADD                  40305
#define IDM_EDIT_PASTE                    40306
#define IDM_EDIT_SWAP                     40307
#define IDM_EDIT_CLEAR                    40308
#define IDM_EDIT_CLEARCLIPBOARD           40309
#define IDM_EDIT_SELECTALL                40310
#define IDM_EDIT_SELECTWORD               40311
#define IDM_EDIT_SELECTLINE               40312
#define IDM_EDIT_MOVELINEUP               40313
#define IDM_EDIT_MOVELINEDOWN             40314
#define IDM_EDIT_DUPLICATELINE            40315
#define IDM_EDIT_CUTLINE                  40316
#define IDM_EDIT_COPYLINE                 40317
#define IDM_EDIT_DELETELINE               40318
#define IDM_EDIT_DELETELINELEFT           40319
#define IDM_EDIT_DELETELINERIGHT          40320
#define IDM_EDIT_COLUMNWRAP               40321
#define IDM_EDIT_SPLITLINES               40322
#define IDM_EDIT_JOINLINES                40323
#define IDM_EDIT_JOINLINES_PARA           40324
#define IDM_EDIT_INDENT                   40325
#define IDM_EDIT_UNINDENT                 40326
#define IDM_EDIT_ENCLOSESELECTION         40327
#define IDM_EDIT_SELECTIONDUPLICATE       40328
#define IDM_EDIT_PADWITHSPACES            40329
#define IDM_EDIT_STRIP1STCHAR             40330
#define IDM_EDIT_STRIPLASTCHAR            40331
#define IDM_EDIT_TRIMLINES                40332
#define IDM_EDIT_COMPRESSWS               40333
#define IDM_EDIT_MERGEBLANKLINES          40334
#define IDM_EDIT_REMOVEBLANKLINES         40335
#define IDM_EDIT_MODIFYLINES              40336
#define IDM_EDIT_SORTLINES                40337
#define IDM_EDIT_ALIGN                    40338
#define IDM_EDIT_CONVERTUPPERCASE         40339
#define IDM_EDIT_CONVERTLOWERCASE         40340
#define IDM_EDIT_INVERTCASE               40341
#define IDM_EDIT_TITLECASE                40342
#define IDM_EDIT_SENTENCECASE             40343
#define IDM_EDIT_CONVERTTABS              40344
#define IDM_EDIT_CONVERTSPACES            40345
#define IDM_EDIT_CONVERTTABS2             40346
#define IDM_EDIT_CONVERTSPACES2           40347
#define IDM_EDIT_INSERT_TAG               40348
#define IDM_EDIT_INSERT_ENCODING          40349
#define IDM_EDIT_INSERT_SHORTDATE         40350
#define IDM_EDIT_INSERT_LONGDATE          40351
#define IDM_EDIT_INSERT_FILENAME          40352
#define IDM_EDIT_INSERT_PATHNAME          40353
#define IDM_EDIT_LINECOMMENT              40354
#define IDM_EDIT_STREAMCOMMENT            40355
#define IDM_EDIT_URLENCODE                40356
#define IDM_EDIT_URLDECODE                40357
#define IDM_EDIT_ESCAPECCHARS             40358
#define IDM_EDIT_UNESCAPECCHARS           40359
#define IDM_EDIT_CHAR2HEX                 40360
#define IDM_EDIT_HEX2CHAR                 40361
#define IDM_EDIT_FINDMATCHINGBRACE        40362
#define IDM_EDIT_SELTOMATCHINGBRACE       40363
#define IDM_EDIT_FIND                     40364
#define IDM_EDIT_SAVEFIND                 40365
#define IDM_EDIT_FINDNEXT                 40366
#define IDM_EDIT_FINDPREV                 40367
#define IDM_EDIT_REPLACE                  40368
#define IDM_EDIT_REPLACENEXT              40369
#define IDM_EDIT_GOTOLINE                 40370
#define IDM_EDIT_SELTONEXT                40371
#define IDM_EDIT_SELTOPREV                40372
#define IDM_EDIT_COMPLETEWORD             40373
#define IDM_EDIT_JOINLN_NOSP              40374
#define IDM_EDIT_REMOVEDUPLICATELINES     40375
#define IDM_EDIT_REMOVEEMPTYLINES         40376
#define IDM_VIEW_SCHEME                   40400
#define IDM_VIEW_USE2NDDEFAULT            40401
#define IDM_VIEW_SCHEMECONFIG             40402
#define IDM_VIEW_FONT                     40403
#define IDM_VIEW_WORDWRAP                 40404
#define IDM_VIEW_LONGLINEMARKER           40405
#define IDM_VIEW_SHOWINDENTGUIDES         40406
#define IDM_VIEW_SHOWWHITESPACE           40407
#define IDM_VIEW_SHOWEOLS                 40408
#define IDM_VIEW_WORDWRAPSYMBOLS          40409
#define IDM_VIEW_MATCHBRACES              40410
#define IDM_VIEW_HILITECURRENTLINE        40411
#define IDM_VIEW_LINENUMBERS              40412
#define IDM_VIEW_MARGIN                   40413
#define IDM_VIEW_ZOOMIN                   40414
#define IDM_VIEW_ZOOMOUT                  40415
#define IDM_VIEW_RESETZOOM                40416
#define IDM_VIEW_TABSASSPACES             40417
#define IDM_VIEW_TABSETTINGS              40418
#define IDM_VIEW_WORDWRAPSETTINGS         40419
#define IDM_VIEW_LONGLINESETTINGS         40420
#define IDM_VIEW_AUTOINDENTTEXT           40421
#define IDM_VIEW_AUTOCLOSETAGS            40422
#define IDM_VIEW_REUSEWINDOW              40423
#define IDM_VIEW_STICKYWINPOS             40424
#define IDM_VIEW_ALWAYSONTOP              40425
#define IDM_VIEW_MINTOTRAY                40426
#define IDM_VIEW_TRANSPARENT              40427
#define IDM_VIEW_SINGLEFILEINSTANCE       40428
#define IDM_VIEW_CHANGENOTIFY             40429
#define IDM_VIEW_SHOWFILENAMEONLY         40430
#define IDM_VIEW_SHOWFILENAMEFIRST        40431
#define IDM_VIEW_SHOWFULLPATH             40432
#define IDM_VIEW_SHOWEXCERPT              40433
#define IDM_VIEW_NOESCFUNC                40434
#define IDM_VIEW_ESCMINIMIZE              40435
#define IDM_VIEW_ESCEXIT                  40436
#define IDM_VIEW_SAVEBEFORERUNNINGTOOLS   40437
#define IDM_VIEW_NOSAVERECENT             40438
#define IDM_VIEW_NOSAVEFINDREPL           40439
#define IDM_VIEW_TOOLBAR                  40440
#define IDM_VIEW_CUSTOMIZETB              40441
#define IDM_VIEW_STATUSBAR                40442
#define IDM_VIEW_SAVESETTINGS             40443
#define IDM_VIEW_SAVESETTINGSNOW          40444
#define IDM_VIEW_FOLDING                  40445
#define IDM_VIEW_TOGGLEFOLDS              40446
#define IDM_VIEW_MARKOCCUR_ONOFF          40447
#define IDM_VIEW_MARKOCCUR_CASE           40448
#define IDM_VIEW_MARKOCCUR_WNONE          40449
#define IDM_VIEW_MARKOCCUR_WORD           40450
#define IDM_VIEW_MARKOCCUR_CURRENT        40451
#define IDM_VIEW_MARKOCCUR_VISIBLE        40452
#define IDM_VIEW_AUTOCOMPLETEWORDS        40453
#define IDM_VIEW_ACCELWORDNAV             40454
#define IDM_VIEW_NOPRESERVECARET          40455
#define IDM_VIEW_HYPERLINKHOTSPOTS        40456
#define IDM_VIEW_CURRENTSCHEME            40457
#define IDM_VIEW_SCROLLPASTEOF            40458
#define IDM_HELP_ABOUT                    40500
#define IDM_HELP_CMD                      40501
#define IDM_HELP_ONLINEDOCUMENTATION      40502
#define IDM_TRAY_RESTORE                  40600
#define IDM_TRAY_EXIT                     40601
#define IDT_FILE_NEW                      40700
#define IDT_FILE_OPEN                     40701
#define IDT_FILE_BROWSE                   40702
#define IDT_FILE_SAVE                     40703
#define IDT_EDIT_UNDO                     40704
#define IDT_EDIT_REDO                     40705
#define IDT_EDIT_CUT                      40706
#define IDT_EDIT_COPY                     40707
#define IDT_EDIT_PASTE                    40708
#define IDT_EDIT_FIND                     40709
#define IDT_EDIT_REPLACE                  40710
#define IDT_VIEW_WORDWRAP                 40711
#define IDT_VIEW_ZOOMIN                   40712
#define IDT_VIEW_ZOOMOUT                  40713
#define IDT_VIEW_SCHEME                   40714
#define IDT_VIEW_SCHEMECONFIG             40715
#define IDT_FILE_EXIT                     40716
#define IDT_FILE_SAVEAS                   40717
#define IDT_FILE_SAVECOPY                 40718
#define IDT_EDIT_CLEAR                    40719
#define IDT_FILE_PRINT                    40720
#define IDT_FILE_OPENFAV                  40721
#define IDT_FILE_ADDTOFAV                 40722
#define IDT_VIEW_TOGGLEFOLDS              40723
#define IDT_FILE_LAUNCH                   40724
#define IDS_SAVEPOS                       40800
#define IDS_RESETPOS                      40801
#define IDS_PREVIEW                       40802
#define IDS_ERR_LOADFILE                  50000
#define IDS_ERR_SAVEFILE                  50001
#define IDS_ERR_BROWSE                    50002
#define IDS_ERR_MRUDLG                    50003
#define IDS_ERR_CREATELINK                50004
#define IDS_ERR_PREVWINDISABLED           50005
#define IDS_SELRECT                       50006
#define IDS_BUFFERTOOSMALL                50007
#define IDS_FIND_WRAPFW                   50008
#define IDS_FIND_WRAPRE                   50009
#define IDS_NOTFOUND                      50010
#define IDS_REPLCOUNT                     50011
#define IDS_ASK_ENCODING                  50012
#define IDS_ASK_ENCODING2                 50013
#define IDS_ERR_ENCODINGNA                50014
#define IDS_ERR_UNICODE                   50015
#define IDS_ERR_UNICODE2                  50016
#define IDS_WARN_LOAD_BIG_FILE            50017
#define IDS_ERR_DROP                      50018
#define IDS_ASK_SAVE                      50019
#define IDS_ASK_REVERT                    50020
#define IDS_ASK_RECODE                    50021
#define IDS_ASK_CREATE                    50022
#define IDS_PRINT_HEADER                  50023
#define IDS_PRINT_FOOTER                  50024
#define IDS_PRINT_COLOR                   50025
#define IDS_PRINT_PAGENUM                 50026
#define IDS_PRINT_EMPTY                   50027
#define IDS_PRINT_ERROR                   50028
#define IDS_FAV_SUCCESS                   50029
#define IDS_FAV_FAILURE                   50030
#define IDS_READONLY_MODIFY               50031
#define IDS_READONLY_SAVE                 50032
#define IDS_FILECHANGENOTIFY              50033
#define IDS_FILECHANGENOTIFY2             50034
#define IDS_STICKYWINPOS                  50035
#define IDS_SAVEDSETTINGS                 50036
#define IDS_CREATEINI_FAIL                50037
#define IDS_WRITEINI_FAIL                 50038
#define IDS_SETTINGSNOTSAVED              50039
#define IDS_EXPORT_FAIL                   50040
#define IDS_ERR_ACCESSDENIED              50041
#define IDS_WARN_UNKNOWN_EXT              50042
#define IDS_REGEX_INVALID                 50043
#define IDS_DROP_NO_FILE                  50044
#define IDS_APPLY_DEFAULT_FONT            50045
#define IDS_ERR_UPDATECHECKER             50046
#define IDS_CMDLINEHELP                   60000
#define IDM_EDIT_INSERT_GUID              60001
#define IDC_STATIC                        -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        601
#define _APS_NEXT_COMMAND_VALUE         701
#define _APS_NEXT_CONTROL_VALUE         801
#define _APS_NEXT_SYMED_VALUE           901
#endif
#endif
