//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch Notepad3.rc
//
#define IDR_RT_MANIFEST                   1
#define IDR_MAINWND                     100
#define IDC_FINDTEXT                    100
#define IDC_LINENUM                     100
#define IDC_COMMANDLINE                 100
#define IDD_ABOUT                       100
#define IDC_VERSION                     100
#define IDC_OPENWITHDIR                 100
#define IDC_FILEMRU                     100
#define IDC_STYLELIST                   100
#define IDC_FAVORITESDIR                100
#define IDC_COLUMNWRAP                  100
#define IDC_INFOBOXICON                 100
#define IDC_COPY                        100
#define IDC_ENCODINGLIST                100
#define IDC_SEARCHEXE                   101
#define IDR_POPUPMENU                   101
#define IDC_GETOPENWITHDIR              101
#define IDC_RESIZEGRIP                  101
#define IDD_OPENWITH                    101
#define IDC_REPLACETEXT                 101
#define IDI_RUN                         101
#define IDC_COLNUM                      101
#define IDC_DEFAULTSCHEME               101
#define IDC_GETFAVORITESDIR             101
#define IDC_INFOBOXTEXT                 101
#define IDB_OPEN                        101
#define IDR_ACCFINDREPLACE              101
#define IDC_STYLELABEL                  101
#define IDC_RESIZEGRIP4                 101
#define IDC_NOUNICODEDETECTION          101
#define IDC_COPYRIGHT                   101
#define IDC_STYLEEDIT                   102
#define IDC_FINDCASE                    102
#define IDC_OPENWITHDESCR               102
#define IDC_SAVEMRU                     102
#define IDD_RUN                         102
#define IDC_AUTOSELECT                  102
#define IDC_FAVORITESDESCR              102
#define IDC_INFOBOXCHECK                102
#define IDC_CONSISTENTEOLS              102
#define IDB_PREV                        102
#define IDI_STYLES                      102
#define IDC_ASCIIASUTF8                 102
#define IDC_WEBPAGE                     102
#define IDD_DEFENCODING                 103
#define IDC_FINDWORD                    103
#define IDC_RESIZEGRIP3                 103
#define IDB_NEXT                        103
#define IDC_STYLEFORE                   103
#define IDC_AUTOSTRIPBLANKS             103
#define IDC_ENCODINGFROMFILEVARS        103
#define IDC_WEBPAGE2                    103
#define IDC_MODWEBPAGE2                 104
#define IDD_ENCODING                    104
#define IDC_MOD_PAGE2                   104
#define IDC_FINDSTART                   104
#define IDB_PICK                        104
#define IDC_STYLEBACK                   104
#define IDC_AUTHORNAME                  104
#define IDC_WEBPAGE4                    104
#define IDC_MODWEBPAGE                  105
#define IDD_RECODE                      105
#define IDC_FINDREGEXP                  105
#define IDC_STYLEFONT                   105
#define IDB_ENCODING                    105
#define IDC_EMAIL                       105
#define IDC_NOTE2WEBPAGE                106
#define IDD_DEFEOLMODE                  106
#define IDC_FINDTRANSFORMBS             106
#define IDC_PREVIEW                     106
#define IDC_EMAIL2                      106
#define IDC_NOTE2WEBPAGE2               107
#define IDD_FAVORITES                   107
#define IDC_NOWRAP                      107
#define IDC_STYLEDEFAULT                107
#define IDD_ADDTOFAV                    108
#define IDC_PREVSTYLE                   108
#define IDC_FINDCLOSE                   108
#define IDC_EMAIL3                      108
#define IDC_VERSION2                    108
#define IDD_FILEMRU                     109
#define IDC_FINDPREV                    109
#define IDC_NEXTSTYLE                   109
#define IDD_CHANGENOTIFY                110
#define IDC_IMPORT                      110
#define IDD_MODIFYLINES                 111
#define IDC_EXPORT                      111
#define IDC_MOD_PAGE                    112
#define IDC_REPLACE                     112
#define IDC_TITLE                       112
#define IDD_ALIGN                       112
#define IDC_WEBPAGE3                    112
#define IDD_ENCLOSESELECTION            113
#define IDC_REPLACEALL                  113
#define IDC_STYLELABELS                 113
#define IDD_INSERTTAG                   114
#define IDC_REPLACEINSEL                114
#define IDD_SORT                        115
#define IDC_TOGGLEFINDREPLACE           115
#define IDD_COLUMNWRAP                  116
#define IDD_LINENUM                     117
#define IDD_FIND                        118
#define IDD_REPLACE                     119
#define IDD_STYLESELECT                 120
#define IDD_STYLECONFIG                 121
#define IDD_WORDWRAP                    122
#define IDD_LONGLINES                   123
#define IDD_TABSETTINGS                 124
#define IDD_PAGESETUP                   125
#define IDD_INFOBOX                     126
#define IDD_INFOBOX2                    127
#define IDD_INFOBOX3                    128
#define IDC_BACKSLASHHELP               151
#define IDC_REGEXPHELP                  152
#define IDC_WILDCARDHELP                153
#define IDC_WILDCARDSEARCH              154
#define IDC_SCI_VERSION                 155
#define IDR_MAINWND2                    156
#define IDACC_FIND                      200
#define IDACC_REPLACE                   201
#define IDACC_SAVEPOS                   202
#define IDACC_RESETPOS                  203
#define IDACC_FINDNEXT                  204
#define IDACC_FINDPREV                  205
#define IDACC_REPLACENEXT               206
#define IDACC_SAVEFIND                  207
#define IDACC_SELTONEXT                 208
#define IDACC_SELTOPREV                 209
#define IDC_NFOASOEM                    300
#define IDC_COMPILER                    301
#define IDC_COMPILER2                   302
#define IDD_READPW                      401
#define IDC_CHECK1                      402
#define IDC_EDIT1                       403
#define IDC_EDIT2                       404
#define IDC_CHECK2                      405
#define IDC_STATICPW                    406
#define IDC_CHECK3                      407
#define IDM_SETPASS                     408
#define IDD_PASSWORDS                   409
#define IDC_EDIT3                       410
#define IDS_PASS_FAILURE                411
#define IDS_NOPASS                      412
#define IDS_APPTITLE                    10000
#define IDS_APPTITLE_ELEVATED           10001
#define IDS_APPTITLE_PASTEBOARD         10002
#define IDS_UNTITLED                    10003
#define IDS_TITLEEXCERPT                10004
#define IDS_READONLY                    10005
#define IDS_DOCPOS                      10006
#define IDS_DOCPOS2                     10007
#define IDS_DOCSIZE                     10008
#define IDS_LOADFILE                    10009
#define IDS_SAVEFILE                    10010
#define IDS_PRINTFILE                   10011
#define IDS_SAVINGSETTINGS              10012
#define IDS_LINKDESCRIPTION             10013
#define IDS_FILTER_ALL                  10014
#define IDS_FILTER_EXE                  10015
#define IDS_FILTER_INI                  10016
#define IDS_OPENWITH                    10017
#define IDS_FAVORITES                   10018
#define IDS_BACKSLASHHELP               10019
#define IDS_REGEXPHELP                  10020
#define IDS_WILDCARDHELP                10021
#define CMD_ESCAPE                      20000
#define CMD_SHIFTESC                    20001
#define CMD_SHIFTCTRLENTER              20002
#define CMD_CTRLLEFT                    20003
#define CMD_CTRLRIGHT                   20004
#define CMD_BACK                        20005
#define CMD_CTRLBACK                    20006
#define CMD_DEL                         20007
#define CMD_CTRLDEL                     20008
#define CMD_CTRLTAB                     20009
#define CMD_RECODEDEFAULT               20010
#define CMD_RECODEANSI                  20011
#define CMD_RECODEOEM                   20012
#define CMD_RELOADASCIIASUTF8           20013
#define CMD_RELOADNOFILEVARS            20014
#define CMD_LEXDEFAULT                  20015
#define CMD_LEXHTML                     20016
#define CMD_LEXXML                      20017
#define CMD_TIMESTAMPS                  20018
#define CMD_WEBACTION1                  20019
#define CMD_WEBACTION2                  20020
#define CMD_FINDNEXTSEL                 20021
#define CMD_FINDPREVSEL                 20022
#define CMD_INCLINELIMIT                20023
#define CMD_DECLINELIMIT                20024
#define CMD_STRINGIFY                   20025
#define CMD_STRINGIFY2                  20026
#define CMD_EMBRACE                     20027
#define CMD_EMBRACE2                    20028
#define CMD_EMBRACE3                    20029
#define CMD_EMBRACE4                    20030
#define CMD_INCREASENUM                 20031
#define CMD_DECREASENUM                 20032
#define CMD_TOGGLETITLE                 20033
#define CMD_JUMP2SELSTART               20034
#define CMD_JUMP2SELEND                 20035
#define CMD_COPYPATHNAME                20036
#define CMD_COPYWINPOS                  20037
#define CMD_DEFAULTWINPOS               20038
#define CMD_OPENINIFILE                 20039
#define CMD_CTRLENTER                   20040
#define IDM_FILE_NEW                    40000
#define IDM_FILE_OPEN                   40001
#define IDM_FILE_REVERT                 40002
#define IDM_FILE_BROWSE                 40003
#define IDM_FILE_SAVE                   40004
#define IDM_FILE_SAVEAS                 40005
#define IDM_FILE_SAVECOPY               40006
#define IDM_FILE_READONLY               40007
#define IDM_FILE_LAUNCH                 40008
#define IDM_FILE_OPENWITH               40009
#define IDM_FILE_RUN                    40010
#define IDM_FILE_NEWWINDOW              40011
#define IDM_FILE_NEWWINDOW2             40012
#define IDM_FILE_PAGESETUP              40013
#define IDM_FILE_PRINT                  40014
#define IDM_FILE_PROPERTIES             40015
#define IDM_FILE_CREATELINK             40016
#define IDM_FILE_OPENFAV                40017
#define IDM_FILE_ADDTOFAV               40018
#define IDM_FILE_MANAGEFAV              40019
#define IDM_FILE_RECENT                 40020
#define IDM_FILE_EXIT                   40021
#define IDM_ENCODING_ANSI               40100
#define IDM_ENCODING_UNICODE            40101
#define IDM_ENCODING_UNICODEREV         40102
#define IDM_ENCODING_UTF8               40103
#define IDM_ENCODING_UTF8SIGN           40104
#define IDM_ENCODING_SELECT             40105
#define IDM_ENCODING_RECODE             40106
#define IDM_ENCODING_SETDEFAULT         40107
#define IDM_LINEENDINGS_CRLF            40200
#define IDM_LINEENDINGS_LF              40201
#define IDM_LINEENDINGS_CR              40202
#define IDM_LINEENDINGS_SETDEFAULT      40203
#define IDM_EDIT_BOOKMARKTOGGLE         40250
#define IDM_EDIT_BOOKMARKNEXT           40251
#define IDM_EDIT_BOOKMARKCLEAR          40252
#define IDM_EDIT_BOOKMARKPREV           40253
#define BME_EDIT_BOOKMARKTOGGLE         40254
#define BME_EDIT_BOOKMARKNEXT           40255
#define BME_EDIT_BOOKMARKCLEAR          40256
#define BME_EDIT_BOOKMARKPREV           40257
#define IDM_EDIT_UNDO                   40300
#define IDM_EDIT_REDO                   40301
#define IDM_EDIT_CUT                    40302
#define IDM_EDIT_COPY                   40303
#define IDM_EDIT_COPYALL                40304
#define IDM_EDIT_COPYADD                40305
#define IDM_EDIT_PASTE                  40306
#define IDM_EDIT_SWAP                   40307
#define IDM_EDIT_CLEAR                  40308
#define IDM_EDIT_CLEARCLIPBOARD         40309
#define IDM_EDIT_SELECTALL              40310
#define IDM_EDIT_SELECTWORD             40311
#define IDM_EDIT_SELECTLINE             40312
#define IDM_EDIT_MOVELINEUP             40313
#define IDM_EDIT_MOVELINEDOWN           40314
#define IDM_EDIT_DUPLICATELINE          40315
#define IDM_EDIT_CUTLINE                40316
#define IDM_EDIT_COPYLINE               40317
#define IDM_EDIT_DELETELINE             40318
#define IDM_EDIT_DELETELINELEFT         40319
#define IDM_EDIT_DELETELINERIGHT        40320
#define IDM_EDIT_COLUMNWRAP             40321
#define IDM_EDIT_SPLITLINES             40322
#define IDM_EDIT_JOINLINES              40323
#define IDM_EDIT_JOINLINESEX            40324
#define IDM_EDIT_INDENT                 40325
#define IDM_EDIT_UNINDENT               40326
#define IDM_EDIT_ENCLOSESELECTION       40327
#define IDM_EDIT_SELECTIONDUPLICATE     40328
#define IDM_EDIT_PADWITHSPACES          40329
#define IDM_EDIT_STRIP1STCHAR           40330
#define IDM_EDIT_STRIPLASTCHAR          40331
#define IDM_EDIT_TRIMLINES              40332
#define IDM_EDIT_COMPRESSWS             40333
#define IDM_EDIT_MERGEBLANKLINES        40334
#define IDM_EDIT_REMOVEBLANKLINES       40335
#define IDM_EDIT_MODIFYLINES            40336
#define IDM_EDIT_SORTLINES              40337
#define IDM_EDIT_ALIGN                  40338
#define IDM_EDIT_CONVERTUPPERCASE       40339
#define IDM_EDIT_CONVERTLOWERCASE       40340
#define IDM_EDIT_INVERTCASE             40341
#define IDM_EDIT_TITLECASE              40342
#define IDM_EDIT_SENTENCECASE           40343
#define IDM_EDIT_CONVERTTABS            40344
#define IDM_EDIT_CONVERTSPACES          40345
#define IDM_EDIT_CONVERTTABS2           40346
#define IDM_EDIT_CONVERTSPACES2         40347
#define IDM_EDIT_INSERT_TAG             40348
#define IDM_EDIT_INSERT_ENCODING        40349
#define IDM_EDIT_INSERT_SHORTDATE       40350
#define IDM_EDIT_INSERT_LONGDATE        40351
#define IDM_EDIT_INSERT_FILENAME        40352
#define IDM_EDIT_INSERT_PATHNAME        40353
#define IDM_EDIT_LINECOMMENT            40354
#define IDM_EDIT_STREAMCOMMENT          40355
#define IDM_EDIT_URLENCODE              40356
#define IDM_EDIT_URLDECODE              40357
#define IDM_EDIT_ESCAPECCHARS           40358
#define IDM_EDIT_UNESCAPECCHARS         40359
#define IDM_EDIT_CHAR2HEX               40360
#define IDM_EDIT_HEX2CHAR               40361
#define IDM_EDIT_FINDMATCHINGBRACE      40362
#define IDM_EDIT_SELTOMATCHINGBRACE     40363
#define IDM_EDIT_FIND                   40364
#define IDM_EDIT_SAVEFIND               40365
#define IDM_EDIT_FINDNEXT               40366
#define IDM_EDIT_FINDPREV               40367
#define IDM_EDIT_REPLACE                40368
#define IDM_EDIT_REPLACENEXT            40369
#define IDM_EDIT_GOTOLINE               40370
#define IDM_EDIT_SELTONEXT              40371
#define IDM_EDIT_SELTOPREV              40372
#define IDM_EDIT_COMPLETEWORD           40373
#define IDM_VIEW_SCHEME                 40400
#define IDM_VIEW_USE2NDDEFAULT          40401
#define IDM_VIEW_SCHEMECONFIG           40402
#define IDM_VIEW_FONT                   40403
#define IDM_VIEW_WORDWRAP               40404
#define IDM_VIEW_LONGLINEMARKER         40405
#define IDM_VIEW_SHOWINDENTGUIDES       40406
#define IDM_VIEW_SHOWWHITESPACE         40407
#define IDM_VIEW_SHOWEOLS               40408
#define IDM_VIEW_WORDWRAPSYMBOLS        40409
#define IDM_VIEW_MATCHBRACES            40410
#define IDM_VIEW_HILITECURRENTLINE      40411
#define IDM_VIEW_LINENUMBERS            40412
#define IDM_VIEW_MARGIN                 40413
#define IDM_VIEW_ZOOMIN                 40414
#define IDM_VIEW_ZOOMOUT                40415
#define IDM_VIEW_RESETZOOM              40416
#define IDM_VIEW_TABSASSPACES           40417
#define IDM_VIEW_TABSETTINGS            40418
#define IDM_VIEW_WORDWRAPSETTINGS       40419
#define IDM_VIEW_LONGLINESETTINGS       40420
#define IDM_VIEW_AUTOINDENTTEXT         40421
#define IDM_VIEW_AUTOCLOSETAGS          40422
#define IDM_VIEW_REUSEWINDOW            40423
#define IDM_VIEW_STICKYWINPOS           40424
#define IDM_VIEW_ALWAYSONTOP            40425
#define IDM_VIEW_MINTOTRAY              40426
#define IDM_VIEW_TRANSPARENT            40427
#define IDM_VIEW_SINGLEFILEINSTANCE     40428
#define IDM_VIEW_CHANGENOTIFY           40429
#define IDM_VIEW_SHOWFILENAMEONLY       40430
#define IDM_VIEW_SHOWFILENAMEFIRST      40431
#define IDM_VIEW_SHOWFULLPATH           40432
#define IDM_VIEW_SHOWEXCERPT            40433
#define IDM_VIEW_NOESCFUNC              40434
#define IDM_VIEW_ESCMINIMIZE            40435
#define IDM_VIEW_ESCEXIT                40436
#define IDM_VIEW_SAVEBEFORERUNNINGTOOLS 40437
#define IDM_VIEW_NOSAVERECENT           40438
#define IDM_VIEW_NOSAVEFINDREPL         40439
#define IDM_VIEW_TOOLBAR                40440
#define IDM_VIEW_CUSTOMIZETB            40441
#define IDM_VIEW_STATUSBAR              40442
#define IDM_VIEW_SAVESETTINGS           40443
#define IDM_VIEW_SAVESETTINGSNOW        40444
#define IDM_VIEW_FOLDING                40445
#define IDM_VIEW_TOGGLEFOLDS            40446
#define IDM_VIEW_MARKOCCURRENCES_OFF    40447
#define IDM_VIEW_MARKOCCURRENCES_BLUE   40448
#define IDM_VIEW_MARKOCCURRENCES_GREEN  40449
#define IDM_VIEW_MARKOCCURRENCES_RED    40450
#define IDM_VIEW_MARKOCCURRENCES_CASE   40451
#define IDM_VIEW_MARKOCCURRENCES_WORD   40452
#define IDM_VIEW_AUTOCOMPLETEWORDS      40453
#define IDM_VIEW_ACCELWORDNAV           40454
#define IDM_VIEW_VIRTSPACERECTSEL       40455
#define IDM_HELP_ABOUT                  40500
#define IDM_HELP_CMD                    40501
#define IDM_TRAY_RESTORE                40600
#define IDM_TRAY_EXIT                   40601
#define IDT_FILE_NEW                    40700
#define IDT_FILE_OPEN                   40701
#define IDT_FILE_BROWSE                 40702
#define IDT_FILE_SAVE                   40703
#define IDT_EDIT_UNDO                   40704
#define IDT_EDIT_REDO                   40705
#define IDT_EDIT_CUT                    40706
#define IDT_EDIT_COPY                   40707
#define IDT_EDIT_PASTE                  40708
#define IDT_EDIT_FIND                   40709
#define IDT_EDIT_REPLACE                40710
#define IDT_VIEW_WORDWRAP               40711
#define IDT_VIEW_ZOOMIN                 40712
#define IDT_VIEW_ZOOMOUT                40713
#define IDT_VIEW_SCHEME                 40714
#define IDT_VIEW_SCHEMECONFIG           40715
#define IDT_FILE_EXIT                   40716
#define IDT_FILE_SAVEAS                 40717
#define IDT_FILE_SAVECOPY               40718
#define IDT_EDIT_CLEAR                  40719
#define IDT_FILE_PRINT                  40720
#define IDT_FILE_OPENFAV                40721
#define IDT_FILE_ADDTOFAV               40722
#define IDT_VIEW_TOGGLEFOLDS            40723
#define IDT_FILE_LAUNCH                 40724
#define SC_SAVEPOS                      40800
#define SC_RESETPOS                     40801
#define IDS_ERR_LOADFILE                50000
#define IDS_ERR_SAVEFILE                50001
#define IDS_ERR_BROWSE                  50002
#define IDS_ERR_MRUDLG                  50003
#define IDS_ERR_CREATELINK              50004
#define IDS_ERR_PREVWINDISABLED         50005
#define IDS_SELRECT                     50006
#define IDS_BUFFERTOOSMALL              50007
#define IDS_FIND_WRAPFW                 50008
#define IDS_FIND_WRAPRE                 50009
#define IDS_NOTFOUND                    50010
#define IDS_REPLCOUNT                   50011
#define IDS_ASK_ENCODING                50012
#define IDS_ASK_ENCODING2               50013
#define IDS_ERR_ENCODINGNA              50014
#define IDS_ERR_UNICODE                 50015
#define IDS_ERR_UNICODE2                50016
#define IDS_WARNLOADBIGFILE             50017
#define IDS_ERR_DROP                    50018
#define IDS_ASK_SAVE                    50019
#define IDS_ASK_REVERT                  50020
#define IDS_ASK_RECODE                  50021
#define IDS_ASK_CREATE                  50022
#define IDS_PRINT_HEADER                50023
#define IDS_PRINT_FOOTER                50024
#define IDS_PRINT_COLOR                 50025
#define IDS_PRINT_PAGENUM               50026
#define IDS_PRINT_EMPTY                 50027
#define IDS_PRINT_ERROR                 50028
#define IDS_FAV_SUCCESS                 50029
#define IDS_FAV_FAILURE                 50030
#define IDS_READONLY_MODIFY             50031
#define IDS_READONLY_SAVE               50032
#define IDS_FILECHANGENOTIFY            50033
#define IDS_FILECHANGENOTIFY2           50034
#define IDS_STICKYWINPOS                50035
#define IDS_SAVEDSETTINGS               50036
#define IDS_CREATEINI_FAIL              50037
#define IDS_WRITEINI_FAIL               50038
#define IDS_SETTINGSNOTSAVED            50039
#define IDS_EXPORT_FAIL                 50040
#define IDS_ERR_ACCESSDENIED            50041
#define IDS_CMDLINEHELP                 60000
#define IDM_EDIT_INSERT_GUID            60001
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                       1
#define _APS_NEXT_RESOURCE_VALUE        600
#define _APS_NEXT_COMMAND_VALUE         700
#define _APS_NEXT_CONTROL_VALUE         800
#define _APS_NEXT_SYMED_VALUE           900
#endif
#endif
