//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Notepad3.rc
//
#define IDC_STATIC                      -1
#define IDR_RT_MANIFEST                 1

#define IDR_MAINWND                     100
#define IDC_FINDTEXT                    101
#define IDC_LINENUM                     102
#define IDD_ABOUT                       104
#define IDC_VERSION                     105
#define IDC_OPENWITHDIR                 106
#define IDC_FILEMRU                     107
#define IDC_STYLELIST                   108
#define IDC_FAVORITESDIR                109
#define IDC_COLUMNWRAP                  110
#define IDC_INFOBOXICON                 111
#define IDC_COPY                        112
#define IDC_ENCODINGLIST                113
#define IDR_POPUPMENU                   115
#define IDC_GETOPENWITHDIR              116
#define IDC_RESIZEGRIP                  117
#define IDD_OPENWITH                    118
#define IDC_REPLACETEXT                 119
#define IDC_COLNUM                      121
#define IDC_DEFAULTSCHEME               122
#define IDC_GETFAVORITESDIR             123
#define IDC_INFOBOXTEXT                 124
#define IDB_OPEN                        125
#define IDR_ACCFINDREPLACE              126
#define IDC_STYLELABEL_ROOT             127
#define IDC_STYLELABEL                  128
#define IDC_STYLEEDIT_ROOT              129
#define IDC_STYLEEDIT                   130
#define IDC_STYLEBACK                   131
#define IDC_STYLEFONT                   132
#define IDC_STYLEDEFAULT                133
#define IDC_PREVIEW                     134
#define IDC_PREVSTYLE                   135
#define IDC_NEXTSTYLE                   136
#define IDC_IMPORT                      137
#define IDC_EXPORT                      138
#define IDC_RESIZEGRIP4                 139
#define IDC_NOUNICODEDETECTION          140
#define IDC_COPYRIGHT                   141
#define IDC_FINDCASE                    142
#define IDC_OPENWITHDESCR               143
#define IDC_SAVEMRU                     144
#define IDC_AUTOSELECT                  146
#define IDC_FAVORITESDESCR              147
#define IDC_INFOBOXCHECK                148
#define IDC_CONSISTENTEOLS              149
#define IDB_PREV                        150
#define IDI_STYLES                      151
#define IDC_ASCIIASUTF8                 152
#define IDC_WEBPAGE                     153
#define IDD_DEFENCODING                 154
#define IDC_FINDWORD                    155
#define IDC_RESIZEGRIP3                 156
#define IDB_NEXT                        157
#define IDC_STYLEFORE                   158
#define IDC_AUTOSTRIPBLANKS             159
#define IDC_ENCODINGFROMFILEVARS        160
#define IDC_WEBPAGE2                    161
#define IDC_PRESERVECARET               162
#define IDC_MODWEBPAGE2                 163
#define IDD_ENCODING                    164
#define IDC_MOD_PAGE2                   165
#define IDC_FINDSTART                   166
#define IDB_PICK                        167
#define IDC_AUTHORNAME                  168
#define IDC_WEBPAGE4                    169
#define IDC_MODWEBPAGE                  170
#define IDD_RECODE                      171
#define IDC_FINDREGEXP                  172
#define IDB_ENCODING                    173
#define IDC_EMAIL                       174
#define IDC_NOTE2WEBPAGE                175
#define IDD_DEFEOLMODE                  176
#define IDC_FINDTRANSFORMBS             177
#define IDC_EMAIL2                      178
#define IDC_NOTE2WEBPAGE2               179
#define IDD_FAVORITES                   180
#define IDC_NOWRAP                      181
#define IDD_ADDTOFAV                    182
#define IDC_FINDCLOSE                   183
#define IDC_EMAIL3                      184
#define IDD_FILEMRU                     186
#define IDC_FINDPREV                    187
#define IDD_CHANGENOTIFY                188
#define IDD_MODIFYLINES                 189
#define IDC_MOD_PAGE                    190
#define IDC_REPLACE                     191
#define IDC_TITLE                       192
#define IDD_ALIGN                       193
#define IDC_WEBPAGE3                    194
#define IDD_ENCLOSESELECTION            195
#define IDC_REPLACEALL                  196
#define IDD_INSERTTAG                   198
#define IDC_REPLACEINSEL                199
#define IDD_SORT                        200
#define IDC_TOGGLEFINDREPLACE           201
#define IDD_COLUMNWRAP                  202
#define IDD_LINENUM                     203
#define IDD_FIND                        204
#define IDD_REPLACE                     205
#define IDD_STYLESELECT                 206
#define IDD_STYLECONFIG                 207
#define IDD_WORDWRAP                    208
#define IDD_LONGLINES                   209
#define IDD_TABSETTINGS                 210
#define IDD_PAGESETUP                   211
#define IDD_INFOBOX                     212
#define IDD_INFOBOX2                    213
#define IDD_INFOBOX3                    214
#define IDT_TIMER_MRKALL                215
#define IDC_ALL_OCCURRENCES             216
#define IDC_DOT_MATCH_ALL               217
#define IDT_TIMER_MAIN_MRKALL           218
#define IDT_TIMER_UPDATE_HOTSPOT        219
#define IDC_BACKSLASHHELP               220
#define IDC_REGEXPHELP                  221
#define IDC_WILDCARDHELP                222
#define IDC_WILDCARDSEARCH              223
#define IDC_SCI_VERSION                 224
#define IDR_MAINWNDTB                   225
#define IDC_REMOVE                      226
#define IDC_SWAPSTRG                    227
#define IDC_CHECK_OCC                   228
#define IDC_PRINTER                     229
#define IDC_USEASREADINGFALLBACK        230
#define IDR_ACCCUSTOMSCHEMES            231
#define IDC_NOANSICPDETECTION           232
#define IDC_REMEMBERSEARCHPATTERN       233
#define IDC_TOGGLE_VISIBILITY           234
#define IDC_DOC_MODIFIED                235
#define IDT_TIMER_UPDATE_STATUSBAR      236
#define IDT_TIMER_UPDATE_TOOLBAR        237
#define ___SCI_CMD__SCEN_KILLFOCUS___   256
#define IDACC_FIND                      302
#define IDACC_REPLACE                   303
#define IDACC_SAVEPOS                   304
#define IDACC_RESETPOS                  305
#define IDACC_FINDNEXT                  306
#define IDACC_FINDPREV                  307
#define IDACC_REPLACENEXT               308
#define IDACC_SAVEFIND                  309
#define IDACC_SELTONEXT                 310
#define IDACC_SELTOPREV                 311
#define IDACC_VIEWSCHEMECONFIG          312
#define IDACC_PREVIEW                   313
#define IDC_NFOASOEM                    400
#define IDC_COMPILER                    401
#define IDC_SETCURLEXERTV               402
#define IDD_READPW                      403
#define IDC_CHECK1                      404
#define IDC_EDIT1                       405
#define IDC_EDIT2                       406
#define IDC_CHECK2                      407
#define IDC_STATICPW                    408
#define IDC_CHECK3                      409
#define IDD_PASSWORDS                   411
#define IDC_EDIT3                       412
#define IDS_FR_STATUS_TEXT              417
#define IDC_CHECK4                      418
#define ___SCI_CMD__SCEN_SETFOCUS___    512
#define IDR_MAINWNDTB2                  550
#define IDR_MAINWND128                  551
#define IDC_RICHEDITABOUT               552
#define IDC_COPYVERSTRG                 553
#define IDR_RIZBITMAP                   554
#define IDC_RIZONEBMP                   555
#define ___SCI_CMD__SCEN_CHANGE___      768

#define IDS_WARN_PREF_LNG_NOT_AVAIL     4000

#define IDS_FR_STATUS_FMT               5000
#define IDS_STATUS_DOCLINE              5001
#define IDS_STATUS_DOCCOLUMN            5002
#define IDS_STATUS_DOCCOLUMN2           5003
#define IDS_STATUS_SELECTION            5004
#define IDS_STATUS_SELCTLINES           5015
#define IDS_STATUS_SELCTBYTES           5016
#define IDS_STATUS_OCCURRENCE           5017
#define IDS_STATUS_DOCSIZE              5018



#include "../language/common_res.h"

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        50047
#define _APS_NEXT_COMMAND_VALUE         40606
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
